INFO:django.utils.autoreload:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
Using proactor: IocpProactor
2021-05-27 23:27:15,689
2021-05-27 23:27:15,691
2021-05-27 23:27:46,494:INFO
2021-05-27 23:27:46,495:DEBUG
2021-05-27 23:30:04,010:INFO:HR login successful
2021-05-27 23:30:04,231:INFO:HR session starts
2021-05-27 23:30:07,936:INFO:HR/employee session ends
2021-05-27 23:37:55,404:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-05-27 23:37:55,404:DEBUG:Using proactor: IocpProactor
2021-05-27 23:38:02,405:INFO:HR login successful
2021-05-27 23:38:02,596:INFO:HR session starts
2021-05-27 23:38:03,550:INFO:Getting employees details
2021-05-27 23:38:07,502:INFO:Employee deleted successfully
2021-05-27 23:38:10,965:INFO:Update the employee
2021-05-27 23:38:15,516:ERROR:Error in updating employee name
2021-05-27 23:38:15,517:ERROR:Error in updating employee address
2021-05-27 23:38:24,304:INFO:Employee updated successfully
2021-05-27 23:38:24,316:INFO:Getting employees details
2021-05-27 23:38:27,029:INFO:HR/employee session ends
2021-05-27 23:38:27,034:INFO:HR/employee logout
2021-05-28 11:22:16,033:WARNING:Not Found: /favicon.ico
2021-05-28 11:24:53,320:INFO:HR login successful
2021-05-28 11:24:53,548:INFO:HR session starts
2021-05-28 11:24:55,283:INFO:Getting employees details
2021-05-28 11:34:51,782:ERROR:Internal Server Error: /empdashboard
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'kanishk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 76, in empdashboard
    employee = empTable.objects.get(id=id2)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'kanishk'.
2021-05-28 11:40:34,482:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-05-28 11:40:34,498:DEBUG:Using proactor: IocpProactor
