INFO:django.utils.autoreload:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
Using proactor: IocpProactor
2021-05-27 23:27:15,689
2021-05-27 23:27:15,691
2021-05-27 23:27:46,494:INFO
2021-05-27 23:27:46,495:DEBUG
2021-05-27 23:30:04,010:INFO:HR login successful
2021-05-27 23:30:04,231:INFO:HR session starts
2021-05-27 23:30:07,936:INFO:HR/employee session ends
2021-05-27 23:37:55,404:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-05-27 23:37:55,404:DEBUG:Using proactor: IocpProactor
2021-05-27 23:38:02,405:INFO:HR login successful
2021-05-27 23:38:02,596:INFO:HR session starts
2021-05-27 23:38:03,550:INFO:Getting employees details
2021-05-27 23:38:07,502:INFO:Employee deleted successfully
2021-05-27 23:38:10,965:INFO:Update the employee
2021-05-27 23:38:15,516:ERROR:Error in updating employee name
2021-05-27 23:38:15,517:ERROR:Error in updating employee address
2021-05-27 23:38:24,304:INFO:Employee updated successfully
2021-05-27 23:38:24,316:INFO:Getting employees details
2021-05-27 23:38:27,029:INFO:HR/employee session ends
2021-05-27 23:38:27,034:INFO:HR/employee logout
2021-05-28 11:22:16,033:WARNING:Not Found: /favicon.ico
2021-05-28 11:24:53,320:INFO:HR login successful
2021-05-28 11:24:53,548:INFO:HR session starts
2021-05-28 11:24:55,283:INFO:Getting employees details
2021-05-28 11:34:51,782:ERROR:Internal Server Error: /empdashboard
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'kanishk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 76, in empdashboard
    employee = empTable.objects.get(id=id2)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'kanishk'.
2021-05-28 11:40:34,482:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-05-28 11:40:34,498:DEBUG:Using proactor: IocpProactor
2021-05-28 11:47:57,288:INFO:Employee login successful
2021-05-28 11:47:57,494:INFO:Employee session starts
2021-05-28 11:48:11,359:INFO:HR/employee session ends
2021-05-28 11:48:11,364:INFO:HR/employee logout
2021-05-28 11:52:23,092:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-28 11:52:23,095:DEBUG:Using proactor: IocpProactor
2021-05-28 11:52:41,496:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-28 11:52:41,497:DEBUG:Using proactor: IocpProactor
2021-05-28 11:52:54,144:INFO:Employee login successful
2021-05-28 11:52:54,394:INFO:Employee session starts
2021-05-28 11:52:56,321:INFO:HR/employee session ends
2021-05-28 11:52:56,329:INFO:HR/employee logout
2021-05-28 11:54:01,373:INFO:C:\Users\kanis\projects\HR\templates\HRProfile.html changed, reloading.
2021-05-28 11:54:01,375:DEBUG:Using proactor: IocpProactor
2021-05-28 11:54:08,197:INFO:HR login successful
2021-05-28 11:54:08,346:INFO:HR session starts
2021-05-28 11:54:09,546:INFO:Getting employees details
2021-05-28 11:54:11,062:INFO:HR/employee session ends
2021-05-28 11:54:11,070:INFO:HR/employee logout
2021-05-28 11:58:27,358:INFO:HR login successful
2021-05-28 11:58:27,515:INFO:HR session starts
2021-05-28 11:58:47,051:ERROR:Error in name
2021-05-28 11:58:47,051:ERROR:Error in address
2021-05-28 21:56:59,816:DEBUG:Using proactor: IocpProactor
2021-05-29 00:23:56,100:WARNING:Not Found: /
2021-05-29 00:23:56,641:WARNING:Not Found: /favicon.ico
2021-05-29 12:45:43,214:DEBUG:Using proactor: IocpProactor
2021-05-29 16:51:33,300:INFO:Employee login successful
2021-05-29 16:51:33,559:INFO:Employee session starts
2021-05-29 16:51:35,159:INFO:Update the employee
2021-05-29 16:51:41,196:INFO:Employee updated successfully
2021-05-29 16:52:10,047:INFO:Update the employee
2021-05-29 16:52:13,352:INFO:HR/employee session ends
2021-05-29 16:52:13,356:INFO:HR/employee logout
2021-05-29 20:17:25,664:WARNING:Not Found: /favicon.ico
2021-05-29 20:27:53,709:INFO:HR login successful
2021-05-29 20:27:53,885:INFO:HR session starts
2021-05-29 20:27:58,522:INFO:Getting employees details
2021-05-29 20:28:31,992:INFO:HR/employee session ends
2021-05-29 20:28:32,000:INFO:HR/employee logout
2021-05-29 20:28:39,914:WARNING:Wrong session
2021-05-29 22:07:38,089:DEBUG:Using proactor: IocpProactor
2021-05-29 22:07:57,674:INFO:Employee login successful
2021-05-29 22:07:58,032:INFO:Employee session starts
2021-05-29 22:08:03,841:INFO:Update the employee
2021-05-29 22:08:11,981:INFO:Employee updated successfully
2021-05-29 22:08:30,122:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-29 22:08:30,123:DEBUG:Using proactor: IocpProactor
2021-05-29 22:08:43,583:INFO:Employee login successful
2021-05-29 22:08:43,794:INFO:Employee session starts
2021-05-29 22:08:44,947:ERROR:Internal Server Error: /empdashboard
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 78, in empdashboard
    return render(request, 'EmployeeProfile.html', {'employee': employee})
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'employeeEdit' not found. 'employeeEdit' is not a valid view function or pattern name.
2021-05-29 22:11:17,129:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-29 22:11:17,132:DEBUG:Using proactor: IocpProactor
2021-05-29 22:11:29,099:INFO:Employee login successful
2021-05-29 22:11:29,366:INFO:Employee session starts
2021-05-29 22:15:00,388:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-29 22:15:00,390:DEBUG:Using proactor: IocpProactor
2021-05-29 22:15:20,282:INFO:Employee login successful
2021-05-29 22:15:20,512:INFO:Employee session starts
2021-05-29 22:15:24,543:INFO:Update the employee
2021-05-29 22:15:32,931:INFO:Employee updated successfully
2021-05-29 22:16:35,434:INFO:HR/employee session ends
2021-05-29 22:16:35,443:INFO:HR/employee logout
2021-05-30 12:10:47,820:DEBUG:Using proactor: IocpProactor
2021-05-30 12:12:23,207:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:12:23,207:DEBUG:Using proactor: IocpProactor
2021-05-30 12:12:30,240:WARNING:Not Found: /favicon.ico
2021-05-30 12:12:42,455:INFO:Employee login successful
2021-05-30 12:12:42,639:INFO:Employee session starts
2021-05-30 12:13:00,305:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:13:00,305:DEBUG:Using proactor: IocpProactor
2021-05-30 12:13:02,728:INFO:Employee session starts
2021-05-30 12:13:03,594:INFO:Employee session starts
2021-05-30 12:14:07,024:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:14:07,024:DEBUG:Using proactor: IocpProactor
2021-05-30 12:14:11,716:INFO:Employee session starts
2021-05-30 12:14:32,694:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:14:32,694:DEBUG:Using proactor: IocpProactor
2021-05-30 12:14:35,174:INFO:Employee session starts
2021-05-30 12:15:22,303:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:15:22,303:DEBUG:Using proactor: IocpProactor
2021-05-30 12:15:25,713:INFO:Employee session starts
2021-05-30 12:15:43,075:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:15:43,075:DEBUG:Using proactor: IocpProactor
2021-05-30 12:15:44,701:INFO:Employee session starts
2021-05-30 12:16:37,916:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:16:37,916:DEBUG:Using proactor: IocpProactor
2021-05-30 12:16:40,938:INFO:Employee session starts
2021-05-30 12:16:54,551:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:16:54,551:DEBUG:Using proactor: IocpProactor
2021-05-30 12:16:56,485:INFO:Employee session starts
2021-05-30 12:17:25,679:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:17:25,679:DEBUG:Using proactor: IocpProactor
2021-05-30 12:17:28,131:INFO:Employee session starts
2021-05-30 12:18:04,451:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:18:04,451:DEBUG:Using proactor: IocpProactor
2021-05-30 12:18:06,245:INFO:Employee session starts
2021-05-30 12:19:13,461:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-05-30 12:19:13,461:DEBUG:Using proactor: IocpProactor
2021-05-30 12:19:15,223:INFO:Employee session starts
2021-05-30 12:20:17,014:INFO:HR/employee session ends
2021-05-30 12:20:17,022:INFO:HR/employee logout
2021-05-30 22:18:45,679:DEBUG:Using proactor: IocpProactor
2021-06-02 16:02:40,668:DEBUG:Using proactor: IocpProactor
2021-06-02 16:02:49,948:DEBUG:Using proactor: IocpProactor
2021-06-02 16:09:46,652:DEBUG:Using proactor: IocpProactor
2021-06-02 16:09:54,293:DEBUG:Using proactor: IocpProactor
2021-06-02 16:21:33,280:WARNING:Not Found: /favicon.ico
2021-06-02 16:24:13,086:DEBUG:Using proactor: IocpProactor
2021-06-02 16:25:43,410:DEBUG:Using proactor: IocpProactor
2021-06-02 16:26:00,160:DEBUG:Using proactor: IocpProactor
2021-06-02 16:26:48,045:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:26:48,045:DEBUG:Using proactor: IocpProactor
2021-06-02 16:30:49,657:INFO:C:\Users\kanis\projects\HR\Management\admin.py changed, reloading.
2021-06-02 16:30:49,657:DEBUG:Using proactor: IocpProactor
2021-06-02 16:32:08,640:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:32:08,640:DEBUG:Using proactor: IocpProactor
2021-06-02 16:34:48,570:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:34:48,570:DEBUG:Using proactor: IocpProactor
2021-06-02 16:35:58,916:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:35:58,931:DEBUG:Using proactor: IocpProactor
2021-06-02 16:36:07,809:DEBUG:Using proactor: IocpProactor
2021-06-02 16:36:19,412:INFO:HR login successful
2021-06-02 16:36:19,684:INFO:HR session starts
2021-06-02 16:36:42,553:ERROR:Internal Server Error: /register
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 35, in register
    e = get_object_or_404(empTable)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
Employee.models.empTable.MultipleObjectsReturned: get() returned more than one empTable -- it returned 6!
2021-06-02 16:40:55,618:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:40:55,618:DEBUG:Using proactor: IocpProactor
2021-06-02 16:41:25,053:INFO:C:\Users\kanis\projects\HR\Management\models.py changed, reloading.
2021-06-02 16:41:25,053:DEBUG:Using proactor: IocpProactor
2021-06-02 16:42:27,279:DEBUG:Using proactor: IocpProactor
2021-06-02 16:42:32,013:DEBUG:Using proactor: IocpProactor
2021-06-02 16:42:37,403:DEBUG:Using proactor: IocpProactor
2021-06-02 16:45:12,945:INFO:C:\Users\kanis\projects\HR\Management\models.py changed, reloading.
2021-06-02 16:45:12,945:DEBUG:Using proactor: IocpProactor
2021-06-02 16:45:22,701:DEBUG:Using proactor: IocpProactor
2021-06-02 16:45:26,639:DEBUG:Using proactor: IocpProactor
2021-06-02 16:51:38,073:INFO:HR login successful
2021-06-02 16:51:38,273:INFO:HR session starts
2021-06-02 16:51:56,824:INFO:Employee registered successfully
2021-06-02 16:51:56,848:INFO:Getting employees details
2021-06-02 16:52:17,037:INFO:Employee deleted successfully
2021-06-02 16:53:37,981:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:53:37,981:DEBUG:Using proactor: IocpProactor
2021-06-02 16:53:42,121:DEBUG:Using proactor: IocpProactor
2021-06-02 16:53:57,482:INFO:HR login successful
2021-06-02 16:53:57,714:INFO:HR session starts
2021-06-02 16:54:17,438:ERROR:Internal Server Error: /register
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 36, in register
    daily = dailyAttendence(empId=e)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 485, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "19": "dailyAttendence.empId" must be a "empTable" instance.
2021-06-02 16:58:07,975:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 16:58:07,975:DEBUG:Using proactor: IocpProactor
2021-06-02 16:58:29,842:ERROR:Internal Server Error: /register
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 38, in register
    daily = dailyAttendence(empId=e, inTime=datetime.now, outTime=datetime.now)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 485, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "20": "dailyAttendence.empId" must be a "empTable" instance.
2021-06-02 16:59:07,544:INFO:Getting employees details
2021-06-02 16:59:10,128:INFO:Employee deleted successfully
2021-06-02 16:59:12,559:INFO:Employee deleted successfully
2021-06-02 17:00:46,420:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 17:00:46,420:DEBUG:Using proactor: IocpProactor
2021-06-02 17:10:25,897:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 17:10:25,913:DEBUG:Using proactor: IocpProactor
2021-06-02 17:10:33,420:ERROR:Internal Server Error: /delete
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 175, in destroy
    employee = empTable.objects.get(id=id2)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Employee.models.empTable.DoesNotExist: empTable matching query does not exist.
2021-06-02 17:10:44,082:INFO:HR login successful
2021-06-02 17:10:44,274:INFO:HR session starts
2021-06-02 17:10:59,008:INFO:Employee registered successfully
2021-06-02 17:10:59,016:INFO:Getting employees details
2021-06-02 17:11:54,444:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 17:11:54,444:DEBUG:Using proactor: IocpProactor
2021-06-02 17:12:04,790:INFO:HR login successful
2021-06-02 17:12:05,022:INFO:HR session starts
2021-06-02 17:12:20,250:INFO:Employee registered successfully
2021-06-02 17:12:20,266:INFO:Getting employees details
2021-06-02 17:12:42,402:INFO:Employee deleted successfully
2021-06-02 17:12:44,630:INFO:Employee deleted successfully
2021-06-02 17:12:48,788:INFO:Employee deleted successfully
2021-06-02 17:12:50,269:INFO:Employee deleted successfully
2021-06-02 17:12:51,498:INFO:Employee deleted successfully
2021-06-02 17:14:32,702:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-02 17:14:32,702:DEBUG:Using proactor: IocpProactor
2021-06-03 13:48:19,654:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 13:48:19,670:DEBUG:Using proactor: IocpProactor
2021-06-03 13:48:43,747:INFO:Employee login successful
2021-06-03 13:48:43,979:INFO:Employee session starts
2021-06-03 13:49:15,651:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 13:49:15,651:DEBUG:Using proactor: IocpProactor
2021-06-03 13:49:17,952:INFO:Employee session starts
2021-06-03 13:49:22,917:INFO:Employee session starts
2021-06-03 13:57:41,302:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-03 13:57:41,302:DEBUG:Using proactor: IocpProactor
2021-06-03 14:00:39,171:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:00:39,171:DEBUG:Using proactor: IocpProactor
2021-06-03 14:04:44,301:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:04:44,301:DEBUG:Using proactor: IocpProactor
2021-06-03 14:05:03,862:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-03 14:05:03,862:DEBUG:Using proactor: IocpProactor
2021-06-03 14:05:09,617:INFO:Employee session starts
2021-06-03 14:05:37,338:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:05:37,338:DEBUG:Using proactor: IocpProactor
2021-06-03 14:05:41,266:INFO:Employee session starts
2021-06-03 14:05:51,435:INFO:HR/employee session ends
2021-06-03 14:05:51,439:INFO:HR/employee logout
2021-06-03 14:05:57,919:INFO:Employee login successful
2021-06-03 14:05:58,072:INFO:Employee session starts
2021-06-03 14:06:45,072:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:06:45,072:DEBUG:Using proactor: IocpProactor
2021-06-03 14:06:47,103:INFO:Employee session starts
2021-06-03 14:06:48,556:INFO:Employee session starts
2021-06-03 14:08:00,139:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:08:00,139:DEBUG:Using proactor: IocpProactor
2021-06-03 14:08:01,909:INFO:Employee session starts
2021-06-03 14:08:14,680:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:08:14,680:DEBUG:Using proactor: IocpProactor
2021-06-03 14:08:24,773:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:08:24,773:DEBUG:Using proactor: IocpProactor
2021-06-03 14:08:27,867:INFO:Employee session starts
2021-06-03 14:09:23,637:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:09:23,637:DEBUG:Using proactor: IocpProactor
2021-06-03 14:09:26,616:INFO:Employee session starts
2021-06-03 14:09:37,127:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:09:37,127:DEBUG:Using proactor: IocpProactor
2021-06-03 14:09:40,403:INFO:Employee session starts
2021-06-03 14:09:59,267:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:09:59,267:DEBUG:Using proactor: IocpProactor
2021-06-03 14:10:01,897:INFO:Employee session starts
2021-06-03 14:11:22,399:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:11:22,399:DEBUG:Using proactor: IocpProactor
2021-06-03 14:11:26,951:INFO:Employee session starts
2021-06-03 14:13:49,608:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:13:49,608:DEBUG:Using proactor: IocpProactor
2021-06-03 14:15:09,167:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:15:09,167:DEBUG:Using proactor: IocpProactor
2021-06-03 14:19:18,668:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:19:18,670:DEBUG:Using proactor: IocpProactor
2021-06-03 14:19:22,277:INFO:Employee session starts
2021-06-03 14:19:53,027:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:19:53,027:DEBUG:Using proactor: IocpProactor
2021-06-03 14:20:00,824:INFO:Employee session starts
2021-06-03 14:20:12,368:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 14:20:12,369:DEBUG:Using proactor: IocpProactor
2021-06-03 14:20:14,270:INFO:Employee session starts
2021-06-03 15:48:47,187:DEBUG:Using proactor: IocpProactor
2021-06-03 15:54:40,908:DEBUG:Using proactor: IocpProactor
2021-06-03 15:55:45,805:DEBUG:Using proactor: IocpProactor
2021-06-03 17:11:02,804:DEBUG:Using proactor: IocpProactor
2021-06-03 19:30:35,719:INFO:HR login successful
2021-06-03 19:30:35,935:INFO:HR session starts
2021-06-03 19:30:50,522:INFO:Employee registered successfully
2021-06-03 19:30:50,546:INFO:Getting employees details
2021-06-03 19:31:00,797:INFO:HR/employee session ends
2021-06-03 19:31:00,805:INFO:HR/employee logout
2021-06-03 19:31:09,008:INFO:Employee login successful
2021-06-03 19:31:09,176:INFO:Employee session starts
2021-06-03 19:31:12,209:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view Management.views.attendanceIn didn't return an HttpResponse object. It returned None instead.
2021-06-03 19:33:34,972:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:33:34,980:DEBUG:Using proactor: IocpProactor
2021-06-03 19:33:39,434:INFO:Employee session starts
2021-06-03 19:33:40,866:INFO:Employee session starts
2021-06-03 19:34:56,457:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:34:56,465:DEBUG:Using proactor: IocpProactor
2021-06-03 19:35:22,608:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:35:22,608:DEBUG:Using proactor: IocpProactor
2021-06-03 19:35:29,202:INFO:Employee session starts
2021-06-03 19:35:30,850:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: Management_dailyattendence.empId_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    atten.save()
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: Management_dailyattendence.empId_id
2021-06-03 19:36:29,186:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:36:29,186:DEBUG:Using proactor: IocpProactor
2021-06-03 19:36:33,893:INFO:Employee session starts
2021-06-03 19:36:35,184:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    atten = dailyAttendence(empId=id2, inTime=inTime, outTime=0)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 485, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\fields\related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "'23'": "dailyAttendence.empId" must be a "empTable" instance.
2021-06-03 19:37:33,086:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:37:33,086:DEBUG:Using proactor: IocpProactor
2021-06-03 19:37:36,428:INFO:Employee session starts
2021-06-03 19:37:37,983:INFO:Employee session starts
2021-06-03 19:38:36,728:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:38:36,728:DEBUG:Using proactor: IocpProactor
2021-06-03 19:38:42,049:INFO:Employee session starts
2021-06-03 19:38:43,119:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 114, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
Management.models.dailyAttendence.MultipleObjectsReturned: get() returned more than one dailyAttendence -- it returned 2!
2021-06-03 19:40:21,714:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:40:21,714:DEBUG:Using proactor: IocpProactor
2021-06-03 19:40:28,753:INFO:Employee session starts
2021-06-03 19:40:30,173:INFO:Employee session starts
2021-06-03 19:41:11,324:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:41:11,324:DEBUG:Using proactor: IocpProactor
2021-06-03 19:41:15,884:INFO:Employee session starts
2021-06-03 19:41:17,188:INFO:Employee session starts
2021-06-03 19:41:46,503:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 19:41:46,503:DEBUG:Using proactor: IocpProactor
2021-06-03 19:41:51,690:INFO:Employee session starts
2021-06-03 19:41:53,194:INFO:Employee session starts
2021-06-03 19:43:20,231:INFO:C:\Users\kanis\projects\HR\Employee\views.py changed, reloading.
2021-06-03 19:43:20,231:DEBUG:Using proactor: IocpProactor
2021-06-03 19:43:25,131:INFO:HR/employee session ends
2021-06-03 19:43:25,139:INFO:HR/employee logout
2021-06-03 19:43:30,022:INFO:HR login successful
2021-06-03 19:43:30,246:INFO:HR session starts
2021-06-03 19:43:46,273:INFO:Employee registered successfully
2021-06-03 19:43:46,289:INFO:Getting employees details
2021-06-03 19:43:49,945:INFO:HR/employee session ends
2021-06-03 19:43:49,953:INFO:HR/employee logout
2021-06-03 21:00:38,740:ERROR:Employee login fails
2021-06-03 21:00:43,073:ERROR:Employee login fails
2021-06-03 21:00:56,329:INFO:Employee login successful
2021-06-03 21:00:56,505:INFO:Employee session starts
2021-06-03 21:01:38,825:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:01:38,825:DEBUG:Using proactor: IocpProactor
2021-06-03 21:01:53,147:INFO:Employee session starts
2021-06-03 21:01:54,146:INFO:Employee session starts
2021-06-03 21:03:20,601:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:03:20,609:DEBUG:Using proactor: IocpProactor
2021-06-03 21:03:25,187:INFO:Employee session starts
2021-06-03 21:03:26,614:INFO:Employee session starts
2021-06-03 21:04:55,078:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:04:55,078:DEBUG:Using proactor: IocpProactor
2021-06-03 21:08:03,394:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:08:03,402:DEBUG:Using proactor: IocpProactor
2021-06-03 21:08:24,053:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:08:24,061:DEBUG:Using proactor: IocpProactor
2021-06-03 21:08:27,883:INFO:Employee session starts
2021-06-03 21:08:39,517:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:08:39,517:DEBUG:Using proactor: IocpProactor
2021-06-03 21:08:41,431:INFO:Employee session starts
2021-06-03 21:08:50,115:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:08:50,115:DEBUG:Using proactor: IocpProactor
2021-06-03 21:08:52,613:INFO:Employee session starts
2021-06-03 21:09:23,551:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:09:23,551:DEBUG:Using proactor: IocpProactor
2021-06-03 21:09:26,024:INFO:Employee session starts
2021-06-03 21:10:15,030:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:10:15,030:DEBUG:Using proactor: IocpProactor
2021-06-03 21:10:17,890:INFO:Employee session starts
2021-06-03 21:10:36,938:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:10:36,938:DEBUG:Using proactor: IocpProactor
2021-06-03 21:10:39,121:INFO:Employee session starts
2021-06-03 21:10:48,729:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:10:48,729:DEBUG:Using proactor: IocpProactor
2021-06-03 21:10:50,580:INFO:Employee session starts
2021-06-03 21:11:12,566:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 21:11:12,574:DEBUG:Using proactor: IocpProactor
2021-06-03 21:11:14,188:INFO:Employee session starts
2021-06-03 21:14:36,280:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:14:36,280:DEBUG:Using proactor: IocpProactor
2021-06-03 21:24:10,217:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:24:10,217:DEBUG:Using proactor: IocpProactor
2021-06-03 21:24:24,049:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:24:24,049:DEBUG:Using proactor: IocpProactor
2021-06-03 21:24:28,891:INFO:Employee session starts
2021-06-03 21:24:30,428:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 121, in attendanceIn
    if(datetime.date(last) < datetime.today() or daily.inTime is 'null'):
TypeError: can't compare datetime.datetime to datetime.date
2021-06-03 21:26:13,966:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:26:13,966:DEBUG:Using proactor: IocpProactor
2021-06-03 21:26:18,843:INFO:Employee session starts
2021-06-03 21:26:20,571:INFO:Employee session starts
2021-06-03 21:26:51,299:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:26:51,299:DEBUG:Using proactor: IocpProactor
2021-06-03 21:26:53,271:INFO:Employee session starts
2021-06-03 21:26:54,601:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 121, in attendanceIn
    print(datetime.date())
TypeError: unbound method datetime.date() needs an argument
2021-06-03 21:27:00,938:INFO:Employee session starts
2021-06-03 21:27:23,790:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:27:23,790:DEBUG:Using proactor: IocpProactor
2021-06-03 21:27:25,767:INFO:Employee session starts
2021-06-03 21:27:27,140:INFO:Employee session starts
2021-06-03 21:28:21,271:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:28:21,271:DEBUG:Using proactor: IocpProactor
2021-06-03 21:29:49,552:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:29:49,552:DEBUG:Using proactor: IocpProactor
2021-06-03 21:29:53,343:INFO:Employee session starts
2021-06-03 21:29:54,849:INFO:Employee session starts
2021-06-03 21:54:34,748:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:54:34,748:DEBUG:Using proactor: IocpProactor
2021-06-03 21:55:51,647:INFO:Employee session starts
2021-06-03 21:55:53,938:INFO:Employee session starts
2021-06-03 21:57:38,773:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 21:57:38,773:DEBUG:Using proactor: IocpProactor
2021-06-03 22:05:04,916:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:05:04,916:DEBUG:Using proactor: IocpProactor
2021-06-03 22:07:44,458:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:07:44,458:DEBUG:Using proactor: IocpProactor
2021-06-03 22:08:11,699:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:08:11,699:DEBUG:Using proactor: IocpProactor
2021-06-03 22:08:15,609:INFO:Employee session starts
2021-06-03 22:08:16,715:INFO:Employee session starts
2021-06-03 22:08:46,596:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:08:46,596:DEBUG:Using proactor: IocpProactor
2021-06-03 22:09:08,453:INFO:Employee session starts
2021-06-03 22:09:09,892:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 135, in attendanceOut
    print(datetime.date(datetime.strptime(outTime, "%Y-%m-%d %H:%M:%S").day))
TypeError: descriptor 'date' for 'datetime.datetime' objects doesn't apply to a 'int' object
2021-06-03 22:09:54,089:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:09:54,089:DEBUG:Using proactor: IocpProactor
2021-06-03 22:09:57,875:INFO:Employee session starts
2021-06-03 22:09:59,282:INFO:Employee session starts
2021-06-03 22:10:27,119:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 22:10:27,119:DEBUG:Using proactor: IocpProactor
2021-06-03 22:10:30,223:INFO:Employee session starts
2021-06-03 22:10:36,823:INFO:Employee session starts
2021-06-03 22:11:19,406:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 22:11:19,406:DEBUG:Using proactor: IocpProactor
2021-06-03 22:11:21,226:INFO:Employee session starts
2021-06-03 22:11:22,555:INFO:Employee session starts
2021-06-03 22:11:49,901:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:11:49,901:DEBUG:Using proactor: IocpProactor
2021-06-03 22:11:51,904:INFO:Employee session starts
2021-06-03 22:11:53,306:INFO:Employee session starts
2021-06-03 22:13:53,084:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:13:53,084:DEBUG:Using proactor: IocpProactor
2021-06-03 22:18:51,222:INFO:Employee session starts
2021-06-03 22:18:52,593:INFO:Employee session starts
2021-06-03 22:20:50,483:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:20:50,483:DEBUG:Using proactor: IocpProactor
2021-06-03 22:20:53,537:INFO:Employee session starts
2021-06-03 22:20:54,424:INFO:Employee session starts
2021-06-03 22:21:10,521:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:21:10,521:DEBUG:Using proactor: IocpProactor
2021-06-03 22:21:12,543:INFO:Employee session starts
2021-06-03 22:21:13,340:INFO:Employee session starts
2021-06-03 22:21:36,530:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:21:36,530:DEBUG:Using proactor: IocpProactor
2021-06-03 22:21:38,189:INFO:Employee session starts
2021-06-03 22:21:39,185:INFO:Employee session starts
2021-06-03 22:22:08,668:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:22:08,668:DEBUG:Using proactor: IocpProactor
2021-06-03 22:22:11,779:INFO:Employee session starts
2021-06-03 22:22:13,196:INFO:Employee session starts
2021-06-03 22:22:55,644:INFO:C:\Users\kanis\projects\HR\templates\EmployeeProfile.html changed, reloading.
2021-06-03 22:22:55,644:DEBUG:Using proactor: IocpProactor
2021-06-03 22:22:58,475:INFO:Employee session starts
2021-06-03 22:23:31,485:INFO:Employee session starts
2021-06-03 22:24:17,348:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:24:17,348:DEBUG:Using proactor: IocpProactor
2021-06-03 22:24:21,016:INFO:Employee session starts
2021-06-03 22:24:22,143:INFO:Employee session starts
2021-06-03 22:24:40,123:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:24:40,123:DEBUG:Using proactor: IocpProactor
2021-06-03 22:24:43,960:INFO:Employee session starts
2021-06-03 22:24:45,096:INFO:Employee session starts
2021-06-03 22:25:08,653:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:25:08,653:DEBUG:Using proactor: IocpProactor
2021-06-03 22:25:13,211:INFO:Employee session starts
2021-06-03 22:25:14,480:INFO:Employee session starts
2021-06-03 22:26:05,432:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:26:05,440:DEBUG:Using proactor: IocpProactor
2021-06-03 22:26:12,250:INFO:Employee session starts
2021-06-03 22:26:13,343:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 147, in attendanceOut
    print(dayThree + 'sec')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2021-06-03 22:27:09,571:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:27:09,579:DEBUG:Using proactor: IocpProactor
2021-06-03 22:28:27,428:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:28:27,428:DEBUG:Using proactor: IocpProactor
2021-06-03 22:28:32,194:INFO:Employee session starts
2021-06-03 22:28:33,743:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 146, in attendanceOut
    dayThree = (currentIn.strftime('%s') - currentOut.strftime('%s'))
ValueError: Invalid format string
2021-06-03 22:28:58,221:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:28:58,221:DEBUG:Using proactor: IocpProactor
2021-06-03 22:29:01,858:INFO:Employee session starts
2021-06-03 22:29:03,159:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 146, in attendanceOut
    dayThree = (currentIn.strftime('%S') - currentOut.strftime('%S'))
TypeError: unsupported operand type(s) for -: 'str' and 'str'
2021-06-03 22:29:49,986:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:29:49,986:DEBUG:Using proactor: IocpProactor
2021-06-03 22:29:54,731:INFO:Employee session starts
2021-06-03 22:29:55,801:INFO:Employee session starts
2021-06-03 22:30:15,009:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:30:15,024:DEBUG:Using proactor: IocpProactor
2021-06-03 22:30:17,933:INFO:Employee session starts
2021-06-03 22:30:19,264:INFO:Employee session starts
2021-06-03 22:30:28,581:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:30:28,581:DEBUG:Using proactor: IocpProactor
2021-06-03 22:30:30,684:INFO:Employee session starts
2021-06-03 22:30:32,533:INFO:Employee session starts
2021-06-03 22:33:14,716:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:33:14,724:DEBUG:Using proactor: IocpProactor
2021-06-03 22:33:20,027:INFO:Employee session starts
2021-06-03 22:33:21,810:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: Management_empattendence.empId_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 149, in attendanceOut
    EmpAtt.save()
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: Management_empattendence.empId_id
2021-06-03 22:33:48,906:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:33:48,906:DEBUG:Using proactor: IocpProactor
2021-06-03 22:33:51,865:INFO:Employee session starts
2021-06-03 22:33:53,437:INFO:Employee session starts
2021-06-03 22:36:15,129:INFO:C:\Users\kanis\projects\HR\Management\models.py changed, reloading.
2021-06-03 22:36:15,129:DEBUG:Using proactor: IocpProactor
2021-06-03 22:36:18,660:DEBUG:Using proactor: IocpProactor
2021-06-03 22:36:33,689:DEBUG:Using proactor: IocpProactor
2021-06-03 22:36:42,749:DEBUG:Using proactor: IocpProactor
2021-06-03 22:36:57,817:INFO:Employee session starts
2021-06-03 22:36:59,354:INFO:Employee session starts
2021-06-03 22:42:43,747:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:42:43,747:DEBUG:Using proactor: IocpProactor
2021-06-03 22:42:48,835:INFO:Employee session starts
2021-06-03 22:42:50,456:INFO:Employee session starts
2021-06-03 22:43:22,016:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-03 22:43:22,016:DEBUG:Using proactor: IocpProactor
2021-06-03 22:43:26,866:INFO:Employee session starts
2021-06-03 22:43:29,563:INFO:Employee session starts
2021-06-03 22:46:37,366:DEBUG:Using proactor: IocpProactor
2021-06-04 12:58:01,638:DEBUG:Using proactor: IocpProactor
2021-06-04 12:58:05,435:DEBUG:Using proactor: IocpProactor
2021-06-04 13:05:35,191:INFO:Employee session starts
2021-06-04 13:05:36,569:INFO:Getting employees attendance
2021-06-04 13:05:36,637:ERROR:Internal Server Error: /attendance
Traceback (most recent call last):
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 167, in attendanceDetails
    return render(request, 'EmployeeAttendance.html', {'details': attendance})
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\kanis\Envs\test\lib\site-packages\django\template\defaulttags.py", line 167, in render
    values = list(values)
TypeError: 'empAttendence' object is not iterable
2021-06-04 13:07:48,831:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-04 13:07:48,832:DEBUG:Using proactor: IocpProactor
2021-06-04 13:07:54,272:INFO:Employee session starts
2021-06-04 13:07:55,228:INFO:Getting employees attendance
2021-06-04 13:08:48,258:INFO:C:\Users\kanis\projects\HR\templates\EmployeeAttendance.html changed, reloading.
2021-06-04 13:08:48,258:DEBUG:Using proactor: IocpProactor
2021-06-04 13:08:51,161:INFO:Getting employees attendance
2021-06-04 13:15:37,820:INFO:C:\Users\kanis\projects\HR\Management\urls.py changed, reloading.
2021-06-04 13:15:37,822:DEBUG:Using proactor: IocpProactor
2021-06-04 13:15:40,196:INFO:HR/employee session ends
2021-06-04 13:15:40,201:INFO:HR/employee logout
2021-06-04 13:15:43,282:INFO:HR login successful
2021-06-04 13:15:43,437:INFO:HR session starts
2021-06-04 13:15:44,382:INFO:Getting all employees attendance
2021-06-04 13:16:28,935:INFO:C:\Users\kanis\projects\HR\Management\views.py changed, reloading.
2021-06-04 13:16:28,935:DEBUG:Using proactor: IocpProactor
2021-06-04 13:16:32,092:INFO:Getting all employees attendance
2021-06-04 13:17:01,945:INFO:C:\Users\kanis\projects\HR\templates\HRAttendance.html changed, reloading.
2021-06-04 13:17:01,945:DEBUG:Using proactor: IocpProactor
2021-06-04 13:17:04,710:INFO:Getting all employees attendance
2021-06-04 13:51:44,177:INFO:HR/employee session ends
2021-06-04 13:51:44,186:INFO:HR/employee logout
2021-06-04 13:53:36,104:INFO:HR login successful
2021-06-04 13:53:36,317:INFO:HR session starts
2021-06-04 13:53:39,825:INFO:Getting employees details
2021-06-04 13:53:44,366:INFO:Getting all employees attendance
2021-06-04 13:54:19,806:INFO:HR/employee session ends
2021-06-04 13:54:19,812:INFO:HR/employee logout
2021-06-04 13:54:26,755:INFO:Employee login successful
2021-06-04 13:54:26,933:INFO:Employee session starts
2021-06-04 13:54:28,784:INFO:Getting employees attendance
2021-06-04 13:54:49,880:INFO:HR/employee session ends
2021-06-04 13:54:49,888:INFO:HR/employee logout
2021-06-04 13:54:50,053:INFO:HR/employee session ends
2021-06-05 10:12:42,233:DEBUG:Using proactor: IocpProactor
2021-06-05 11:09:38,818:DEBUG:Using proactor: IocpProactor
2021-06-05 11:22:29,738:DEBUG:Using proactor: IocpProactor
2021-06-05 11:32:46,705:DEBUG:Using proactor: IocpProactor
2021-06-05 11:37:07,814:DEBUG:Using proactor: IocpProactor
2021-06-05 11:39:49,047:DEBUG:Using proactor: IocpProactor
2021-06-05 12:02:04,129:DEBUG:Using proactor: IocpProactor
2021-06-05 12:02:05,409:INFO:HR login successful
2021-06-05 12:02:44,722:DEBUG:Using proactor: IocpProactor
2021-06-05 12:02:45,931:INFO:HR login successful
2021-06-05 12:03:38,876:DEBUG:Using proactor: IocpProactor
2021-06-05 12:03:40,072:ERROR:HR login fails
2021-06-05 12:05:23,963:DEBUG:Using proactor: IocpProactor
2021-06-05 12:05:25,210:ERROR:HR login fails
2021-06-05 12:05:25,225:INFO:HR login successful
2021-06-05 13:11:27,925:DEBUG:Using proactor: IocpProactor
2021-06-05 13:11:29,175:ERROR:HR login fails
2021-06-05 13:11:29,191:INFO:HR login successful
2021-06-05 13:16:11,269:DEBUG:Using proactor: IocpProactor
2021-06-05 13:16:12,487:ERROR:HR login fails
2021-06-05 13:16:12,503:INFO:HR login successful
2021-06-05 13:17:02,822:DEBUG:Using proactor: IocpProactor
2021-06-05 13:17:04,025:ERROR:HR login fails
2021-06-05 13:17:04,025:INFO:HR login successful
2021-06-05 13:19:41,481:DEBUG:Using proactor: IocpProactor
2021-06-05 13:19:42,590:INFO:Getting employees details
2021-06-05 13:19:42,684:ERROR:HR login fails
2021-06-05 13:19:42,699:INFO:HR login successful
2021-06-05 13:22:56,936:DEBUG:Using proactor: IocpProactor
2021-06-05 13:22:58,050:INFO:Getting employees details
2021-06-05 13:22:58,081:ERROR:Internal Server Error: /employeeEdit
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 98, in employeeEdit
    employee = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Employee.models.empTable.DoesNotExist: empTable matching query does not exist.
2021-06-05 13:22:58,363:ERROR:HR login fails
2021-06-05 13:22:58,363:INFO:HR login successful
2021-06-05 13:26:05,762:DEBUG:Using proactor: IocpProactor
2021-06-05 13:26:06,887:INFO:Getting employees details
2021-06-05 13:26:06,918:ERROR:Internal Server Error: /employeeEdit
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (1)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Employee\views.py", line 98, in employeeEdit
    employee = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (1)'.
2021-06-05 13:26:07,059:ERROR:HR login fails
2021-06-05 13:26:07,059:INFO:HR login successful
2021-06-05 13:26:53,509:DEBUG:Using proactor: IocpProactor
2021-06-05 13:26:54,649:INFO:Getting employees details
2021-06-05 13:26:54,681:INFO:Update the employee
2021-06-05 13:26:54,759:ERROR:HR login fails
2021-06-05 13:26:54,759:INFO:HR login successful
2021-06-05 13:28:35,218:DEBUG:Using proactor: IocpProactor
2021-06-05 13:28:36,343:INFO:Getting employees details
2021-06-05 13:28:36,374:INFO:Update the employee
2021-06-05 13:28:36,436:ERROR:HR login fails
2021-06-05 13:28:36,452:INFO:HR login successful
2021-06-05 13:35:14,436:DEBUG:Using proactor: IocpProactor
2021-06-05 13:35:15,686:ERROR:HR login fails
2021-06-05 13:35:15,702:INFO:HR login successful
2021-06-05 13:36:02,288:DEBUG:Using proactor: IocpProactor
2021-06-05 13:36:03,553:ERROR:HR login fails
2021-06-05 13:36:03,569:INFO:HR login successful
2021-06-05 13:36:47,116:DEBUG:Using proactor: IocpProactor
2021-06-05 13:36:48,257:INFO:Getting employees details
2021-06-05 13:36:48,304:INFO:Update the employee
2021-06-05 13:36:48,382:INFO:Update the employee
2021-06-05 13:36:48,444:ERROR:HR login fails
2021-06-05 13:36:48,444:INFO:HR login successful
2021-06-05 13:37:23,617:DEBUG:Using proactor: IocpProactor
2021-06-05 13:37:24,726:INFO:Getting employees details
2021-06-05 13:37:24,773:INFO:Update the employee
2021-06-05 13:37:24,789:INFO:Update the employee
2021-06-05 13:37:24,851:ERROR:HR login fails
2021-06-05 13:37:24,851:INFO:HR login successful
2021-06-05 13:45:20,399:DEBUG:Using proactor: IocpProactor
2021-06-05 13:45:21,493:INFO:Getting employees details
2021-06-05 13:45:21,540:INFO:Update the employee
2021-06-05 13:45:21,555:INFO:Update the employee
2021-06-05 13:45:21,602:ERROR:HR login fails
2021-06-05 13:45:21,618:INFO:HR login successful
2021-06-05 13:48:29,611:DEBUG:Using proactor: IocpProactor
2021-06-05 13:48:30,767:INFO:Getting employees details
2021-06-05 13:48:30,798:INFO:Update the employee
2021-06-05 13:48:30,814:INFO:Update the employee
2021-06-05 13:48:30,845:INFO:Employee registered successfully
2021-06-05 13:48:30,876:ERROR:HR login fails
2021-06-05 13:48:30,892:INFO:HR login successful
2021-06-05 13:50:56,520:DEBUG:Using proactor: IocpProactor
2021-06-05 13:50:57,660:INFO:Getting employees details
2021-06-05 13:50:57,691:INFO:Update the employee
2021-06-05 13:50:57,707:INFO:Update the employee
2021-06-05 13:50:57,722:INFO:Employee registered successfully
2021-06-05 13:50:57,769:ERROR:HR login fails
2021-06-05 13:50:57,785:INFO:HR login successful
2021-06-05 14:06:14,649:DEBUG:Using proactor: IocpProactor
2021-06-05 14:06:15,805:INFO:Getting employees details
2021-06-05 14:06:15,837:INFO:Update the employee
2021-06-05 14:06:15,852:INFO:Update the employee
2021-06-05 14:06:15,883:INFO:Employee registered successfully
2021-06-05 14:06:15,883:ERROR:Error in name
2021-06-05 14:06:15,883:ERROR:Error in address
2021-06-05 14:06:15,930:ERROR:HR login fails
2021-06-05 14:06:15,930:INFO:HR login successful
2021-06-05 14:07:49,922:DEBUG:Using proactor: IocpProactor
2021-06-05 14:07:51,047:INFO:Getting employees details
2021-06-05 14:07:51,078:INFO:Update the employee
2021-06-05 14:07:51,110:INFO:Update the employee
2021-06-05 14:07:51,125:INFO:Employee registered successfully
2021-06-05 14:07:51,125:ERROR:Error in address
2021-06-05 14:07:51,141:ERROR:Error in name
2021-06-05 14:07:51,188:ERROR:HR login fails
2021-06-05 14:07:51,188:INFO:HR login successful
2021-06-05 14:13:47,436:DEBUG:Using proactor: IocpProactor
2021-06-05 14:13:48,592:INFO:Getting employees details
2021-06-05 14:13:48,639:INFO:Update the employee
2021-06-05 14:13:48,655:INFO:Update the employee
2021-06-05 14:13:48,686:INFO:Employee registered successfully
2021-06-05 14:13:48,686:ERROR:Error in address
2021-06-05 14:13:48,702:ERROR:Error in name
2021-06-05 14:13:48,717:INFO:Employee updated successfully
2021-06-05 14:13:48,717:ERROR:Error in address
2021-06-05 14:13:48,733:ERROR:Error in name
2021-06-05 14:13:48,780:ERROR:HR login fails
2021-06-05 14:13:48,795:INFO:HR login successful
2021-06-05 14:15:29,589:DEBUG:Using proactor: IocpProactor
2021-06-05 14:15:30,870:INFO:Getting employees details
2021-06-05 14:15:30,917:INFO:Update the employee
2021-06-05 14:15:30,948:INFO:Update the employee
2021-06-05 14:15:30,964:INFO:Employee registered successfully
2021-06-05 14:15:30,964:ERROR:Error in address
2021-06-05 14:15:30,979:ERROR:Error in name
2021-06-05 14:15:30,995:INFO:Employee updated successfully
2021-06-05 14:15:30,995:ERROR:Error in updating employee address
2021-06-05 14:15:31,010:ERROR:Error in updating employee name
2021-06-05 14:15:31,057:ERROR:HR login fails
2021-06-05 14:15:31,073:INFO:HR login successful
2021-06-05 14:19:15,878:DEBUG:Using proactor: IocpProactor
2021-06-05 14:19:17,081:INFO:Getting employees details
2021-06-05 14:19:17,128:INFO:Update the employee
2021-06-05 14:19:17,143:INFO:Update the employee
2021-06-05 14:19:17,159:INFO:Employee updated successfully
2021-06-05 14:19:17,174:ERROR:Error in updating employee address
2021-06-05 14:19:17,190:ERROR:Error in updating employee name
2021-06-05 14:19:17,206:INFO:Employee registered successfully
2021-06-05 14:19:17,221:ERROR:Error in address
2021-06-05 14:19:17,221:ERROR:Error in name
2021-06-05 14:19:17,237:INFO:Employee updated successfully
2021-06-05 14:19:17,253:ERROR:Error in updating employee address
2021-06-05 14:19:17,253:ERROR:Error in updating employee name
2021-06-05 14:19:17,315:ERROR:HR login fails
2021-06-05 14:19:17,315:INFO:HR login successful
2021-06-05 14:20:19,103:DEBUG:Using proactor: IocpProactor
2021-06-05 14:20:20,212:INFO:Getting employees details
2021-06-05 14:20:20,259:INFO:Update the employee
2021-06-05 14:20:20,275:INFO:Update the employee
2021-06-05 14:20:20,290:INFO:Employee updated successfully
2021-06-05 14:20:20,306:ERROR:Error in updating employee address
2021-06-05 14:20:20,322:ERROR:Error in updating employee name
2021-06-05 14:20:20,337:INFO:Employee registered successfully
2021-06-05 14:20:20,337:ERROR:Error in address
2021-06-05 14:20:20,353:ERROR:Error in name
2021-06-05 14:20:20,369:INFO:Employee updated successfully
2021-06-05 14:20:20,369:ERROR:Error in updating employee address
2021-06-05 14:20:20,384:ERROR:Error in updating employee name
2021-06-05 14:20:20,431:ERROR:HR login fails
2021-06-05 14:20:20,431:INFO:HR login successful
2021-06-05 14:25:44,020:DEBUG:Using proactor: IocpProactor
2021-06-05 14:25:45,145:INFO:Getting employees details
2021-06-05 14:25:45,192:INFO:Update the employee
2021-06-05 14:25:45,207:INFO:Update the employee
2021-06-05 14:25:45,223:INFO:Employee updated successfully
2021-06-05 14:25:45,239:ERROR:Error in updating employee address
2021-06-05 14:25:45,254:ERROR:Error in updating employee name
2021-06-05 14:25:45,270:INFO:Employee registered successfully
2021-06-05 14:25:45,285:ERROR:Error in address
2021-06-05 14:25:45,285:ERROR:Error in name
2021-06-05 14:25:45,301:INFO:Employee updated successfully
2021-06-05 14:25:45,317:ERROR:Error in updating employee address
2021-06-05 14:25:45,317:ERROR:Error in updating employee name
2021-06-05 14:25:45,364:INFO:Employee login successful
2021-06-05 14:25:45,379:ERROR:HR login fails
2021-06-05 14:25:45,395:INFO:HR login successful
2021-06-05 14:27:34,570:DEBUG:Using proactor: IocpProactor
2021-06-05 14:27:35,835:INFO:Getting employees details
2021-06-05 14:27:35,867:INFO:Update the employee
2021-06-05 14:27:35,882:INFO:Update the employee
2021-06-05 14:27:35,898:INFO:Employee updated successfully
2021-06-05 14:27:35,914:ERROR:Error in updating employee address
2021-06-05 14:27:35,929:ERROR:Error in updating employee name
2021-06-05 14:27:35,945:INFO:Employee registered successfully
2021-06-05 14:27:35,960:ERROR:Error in address
2021-06-05 14:27:35,960:ERROR:Error in name
2021-06-05 14:27:35,976:INFO:Employee updated successfully
2021-06-05 14:27:35,992:ERROR:Error in updating employee address
2021-06-05 14:27:36,007:ERROR:Error in updating employee name
2021-06-05 14:27:36,039:ERROR:Employee login fails
2021-06-05 14:27:36,054:INFO:Employee login successful
2021-06-05 14:27:36,070:ERROR:HR login fails
2021-06-05 14:27:36,070:INFO:HR login successful
2021-06-05 14:37:21,721:DEBUG:Using proactor: IocpProactor
2021-06-05 14:37:22,831:INFO:Getting employees details
2021-06-05 14:37:22,862:INFO:Update the employee
2021-06-05 14:37:22,893:INFO:Update the employee
2021-06-05 14:37:22,893:INFO:Employee updated successfully
2021-06-05 14:37:22,909:ERROR:Error in updating employee address
2021-06-05 14:37:22,925:ERROR:Error in updating employee name
2021-06-05 14:37:22,940:INFO:Employee registered successfully
2021-06-05 14:37:22,956:ERROR:Error in address
2021-06-05 14:37:22,956:ERROR:Error in name
2021-06-05 14:37:22,971:INFO:Employee updated successfully
2021-06-05 14:37:22,987:ERROR:Error in updating employee address
2021-06-05 14:37:23,003:ERROR:Error in updating employee name
2021-06-05 14:37:23,065:ERROR:Employee login fails
2021-06-05 14:37:23,081:INFO:Employee login successful
2021-06-05 14:37:23,096:ERROR:HR login fails
2021-06-05 14:37:23,112:INFO:HR login successful
2021-06-05 14:47:06,191:DEBUG:Using proactor: IocpProactor
2021-06-05 14:47:07,691:INFO:Getting employees details
2021-06-05 14:47:07,738:INFO:Update the employee
2021-06-05 14:47:07,753:INFO:Update the employee
2021-06-05 14:47:07,769:INFO:Employee updated successfully
2021-06-05 14:47:07,785:ERROR:Error in updating employee address
2021-06-05 14:47:07,800:ERROR:Error in updating employee name
2021-06-05 14:47:07,816:INFO:Employee registered successfully
2021-06-05 14:47:07,832:ERROR:Error in address
2021-06-05 14:47:07,832:ERROR:Error in name
2021-06-05 14:47:07,847:INFO:Employee updated successfully
2021-06-05 14:47:07,863:ERROR:Error in updating employee address
2021-06-05 14:47:07,863:ERROR:Error in updating employee name
2021-06-05 14:47:07,910:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendence.DoesNotExist: dailyAttendence matching query does not exist.
2021-06-05 14:47:07,988:ERROR:Employee login fails
2021-06-05 14:47:08,003:INFO:Employee login successful
2021-06-05 14:47:08,019:ERROR:HR login fails
2021-06-05 14:47:08,019:INFO:HR login successful
2021-06-05 14:49:42,554:DEBUG:Using proactor: IocpProactor
2021-06-05 14:49:44,033:INFO:Getting employees details
2021-06-05 14:49:44,071:INFO:Update the employee
2021-06-05 14:49:44,095:INFO:Update the employee
2021-06-05 14:49:44,103:INFO:Employee updated successfully
2021-06-05 14:49:44,119:ERROR:Error in updating employee address
2021-06-05 14:49:44,135:ERROR:Error in updating employee name
2021-06-05 14:49:44,159:INFO:Employee registered successfully
2021-06-05 14:49:44,167:ERROR:Error in address
2021-06-05 14:49:44,175:ERROR:Error in name
2021-06-05 14:49:44,183:INFO:Employee updated successfully
2021-06-05 14:49:44,199:ERROR:Error in updating employee address
2021-06-05 14:49:44,215:ERROR:Error in updating employee name
2021-06-05 14:49:44,255:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendence.DoesNotExist: dailyAttendence matching query does not exist.
2021-06-05 14:49:44,327:ERROR:Employee login fails
2021-06-05 14:49:44,343:INFO:Employee login successful
2021-06-05 14:49:44,359:ERROR:HR login fails
2021-06-05 14:49:44,359:INFO:HR login successful
2021-06-05 14:51:39,894:DEBUG:Using proactor: IocpProactor
2021-06-05 14:51:41,254:INFO:Getting employees details
2021-06-05 14:51:41,316:INFO:Update the employee
2021-06-05 14:51:41,363:INFO:Update the employee
2021-06-05 14:51:41,394:INFO:Employee updated successfully
2021-06-05 14:51:41,426:ERROR:Error in updating employee address
2021-06-05 14:51:41,426:ERROR:Error in updating employee name
2021-06-05 14:51:41,457:INFO:Employee registered successfully
2021-06-05 14:51:41,457:ERROR:Error in address
2021-06-05 14:51:41,473:ERROR:Error in name
2021-06-05 14:51:41,488:INFO:Employee updated successfully
2021-06-05 14:51:41,488:ERROR:Error in updating employee address
2021-06-05 14:51:41,504:ERROR:Error in updating employee name
2021-06-05 14:51:41,551:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendence.DoesNotExist: dailyAttendence matching query does not exist.
2021-06-05 14:51:41,629:ERROR:Employee login fails
2021-06-05 14:51:41,629:INFO:Employee login successful
2021-06-05 14:51:41,644:ERROR:HR login fails
2021-06-05 14:51:41,660:INFO:HR login successful
2021-06-05 14:57:15,247:DEBUG:Using proactor: IocpProactor
2021-06-05 14:57:16,513:INFO:Getting employees details
2021-06-05 14:57:16,607:INFO:Update the employee
2021-06-05 14:57:16,638:INFO:Update the employee
2021-06-05 14:57:16,653:INFO:Employee updated successfully
2021-06-05 14:57:16,685:ERROR:Error in updating employee address
2021-06-05 14:57:16,700:ERROR:Error in updating employee name
2021-06-05 14:57:16,732:INFO:Employee registered successfully
2021-06-05 14:57:16,747:ERROR:Error in address
2021-06-05 14:57:16,763:ERROR:Error in name
2021-06-05 14:57:16,778:INFO:Employee updated successfully
2021-06-05 14:57:16,794:ERROR:Error in updating employee address
2021-06-05 14:57:16,810:ERROR:Error in updating employee name
2021-06-05 14:57:16,841:INFO:Getting all employees attendance
2021-06-05 14:57:16,919:ERROR:Employee login fails
2021-06-05 14:57:16,935:INFO:Employee login successful
2021-06-05 14:57:16,966:ERROR:HR login fails
2021-06-05 14:57:16,982:INFO:HR login successful
2021-06-05 14:58:37,665:DEBUG:Using proactor: IocpProactor
2021-06-05 14:58:39,040:INFO:Getting employees details
2021-06-05 14:58:39,071:INFO:Update the employee
2021-06-05 14:58:39,087:INFO:Update the employee
2021-06-05 14:58:39,102:INFO:Employee updated successfully
2021-06-05 14:58:39,118:ERROR:Error in updating employee address
2021-06-05 14:58:39,133:ERROR:Error in updating employee name
2021-06-05 14:58:39,165:INFO:Employee registered successfully
2021-06-05 14:58:39,180:ERROR:Error in address
2021-06-05 14:58:39,180:ERROR:Error in name
2021-06-05 14:58:39,196:INFO:Employee updated successfully
2021-06-05 14:58:39,212:ERROR:Error in updating employee address
2021-06-05 14:58:39,227:ERROR:Error in updating employee name
2021-06-05 14:58:39,258:INFO:Getting all employees attendance
2021-06-05 14:58:39,305:ERROR:Employee login fails
2021-06-05 14:58:39,321:INFO:Employee login successful
2021-06-05 14:58:39,337:ERROR:HR login fails
2021-06-05 14:58:39,352:INFO:HR login successful
2021-06-05 14:59:06,271:DEBUG:Using proactor: IocpProactor
2021-06-05 14:59:07,615:INFO:Getting employees details
2021-06-05 14:59:07,646:INFO:Update the employee
2021-06-05 14:59:07,662:INFO:Update the employee
2021-06-05 14:59:07,678:INFO:Employee updated successfully
2021-06-05 14:59:07,693:ERROR:Error in updating employee address
2021-06-05 14:59:07,709:ERROR:Error in updating employee name
2021-06-05 14:59:07,724:INFO:Employee registered successfully
2021-06-05 14:59:07,740:ERROR:Error in address
2021-06-05 14:59:07,740:ERROR:Error in name
2021-06-05 14:59:07,756:INFO:Employee updated successfully
2021-06-05 14:59:07,771:ERROR:Error in updating employee address
2021-06-05 14:59:07,787:ERROR:Error in updating employee name
2021-06-05 14:59:07,803:INFO:Getting all employees attendance
2021-06-05 14:59:07,849:ERROR:Employee login fails
2021-06-05 14:59:07,865:INFO:Employee login successful
2021-06-05 14:59:07,881:ERROR:HR login fails
2021-06-05 14:59:07,881:INFO:HR login successful
2021-06-05 15:00:34,492:DEBUG:Using proactor: IocpProactor
2021-06-05 15:00:35,664:INFO:Getting employees details
2021-06-05 15:00:35,695:INFO:Update the employee
2021-06-05 15:00:35,711:INFO:Update the employee
2021-06-05 15:00:35,727:INFO:Employee updated successfully
2021-06-05 15:00:35,742:ERROR:Error in updating employee address
2021-06-05 15:00:35,758:ERROR:Error in updating employee name
2021-06-05 15:00:35,774:INFO:Employee registered successfully
2021-06-05 15:00:35,789:ERROR:Error in address
2021-06-05 15:00:35,789:ERROR:Error in name
2021-06-05 15:00:35,805:INFO:Employee updated successfully
2021-06-05 15:00:35,820:ERROR:Error in updating employee address
2021-06-05 15:00:35,820:ERROR:Error in updating employee name
2021-06-05 15:00:35,852:INFO:Getting all employees attendance
2021-06-05 15:00:35,899:ERROR:Employee login fails
2021-06-05 15:00:35,914:INFO:Employee login successful
2021-06-05 15:00:35,930:ERROR:HR login fails
2021-06-05 15:00:35,930:INFO:HR login successful
2021-06-05 15:01:40,015:DEBUG:Using proactor: IocpProactor
2021-06-05 15:01:41,484:INFO:Getting employees details
2021-06-05 15:01:41,515:INFO:Update the employee
2021-06-05 15:01:41,530:INFO:Update the employee
2021-06-05 15:01:41,546:INFO:Employee updated successfully
2021-06-05 15:01:41,562:ERROR:Error in updating employee address
2021-06-05 15:01:41,577:ERROR:Error in updating employee name
2021-06-05 15:01:41,593:INFO:Employee registered successfully
2021-06-05 15:01:41,609:ERROR:Error in address
2021-06-05 15:01:41,609:ERROR:Error in name
2021-06-05 15:01:41,624:INFO:Employee updated successfully
2021-06-05 15:01:41,640:ERROR:Error in updating employee address
2021-06-05 15:01:41,655:ERROR:Error in updating employee name
2021-06-05 15:01:41,671:INFO:Getting all employees attendance
2021-06-05 15:01:41,718:ERROR:Employee login fails
2021-06-05 15:01:41,734:INFO:Employee login successful
2021-06-05 15:01:41,749:ERROR:HR login fails
2021-06-05 15:01:41,749:INFO:HR login successful
2021-06-05 15:02:01,557:DEBUG:Using proactor: IocpProactor
2021-06-05 15:02:02,932:INFO:Getting employees details
2021-06-05 15:02:02,963:INFO:Update the employee
2021-06-05 15:02:02,994:INFO:Update the employee
2021-06-05 15:02:02,994:INFO:Employee updated successfully
2021-06-05 15:02:03,010:ERROR:Error in updating employee address
2021-06-05 15:02:03,025:ERROR:Error in updating employee name
2021-06-05 15:02:03,057:INFO:Employee registered successfully
2021-06-05 15:02:03,057:ERROR:Error in address
2021-06-05 15:02:03,072:ERROR:Error in name
2021-06-05 15:02:03,072:INFO:Employee updated successfully
2021-06-05 15:02:03,088:ERROR:Error in updating employee address
2021-06-05 15:02:03,104:ERROR:Error in updating employee name
2021-06-05 15:02:03,119:INFO:Getting all employees attendance
2021-06-05 15:02:03,150:ERROR:Internal Server Error: /attendance
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 165, in attendanceDetails
    attendance = empAttendence.objects.filter(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 15:02:03,244:ERROR:Employee login fails
2021-06-05 15:02:03,260:INFO:Employee login successful
2021-06-05 15:02:03,275:ERROR:HR login fails
2021-06-05 15:02:03,275:INFO:HR login successful
2021-06-05 15:06:58,312:DEBUG:Using proactor: IocpProactor
2021-06-05 15:06:59,577:INFO:Getting employees details
2021-06-05 15:06:59,624:INFO:Update the employee
2021-06-05 15:06:59,639:INFO:Update the employee
2021-06-05 15:06:59,655:INFO:Employee updated successfully
2021-06-05 15:06:59,670:ERROR:Error in updating employee address
2021-06-05 15:06:59,686:ERROR:Error in updating employee name
2021-06-05 15:06:59,702:INFO:Employee registered successfully
2021-06-05 15:06:59,702:ERROR:Error in address
2021-06-05 15:06:59,717:ERROR:Error in name
2021-06-05 15:06:59,733:INFO:Employee updated successfully
2021-06-05 15:06:59,733:ERROR:Error in updating employee address
2021-06-05 15:06:59,764:ERROR:Error in updating employee name
2021-06-05 15:06:59,780:INFO:Getting all employees attendance
2021-06-05 15:06:59,811:INFO:Getting employees attendance
2021-06-05 15:06:59,842:ERROR:Employee login fails
2021-06-05 15:06:59,858:INFO:Employee login successful
2021-06-05 15:06:59,874:ERROR:HR login fails
2021-06-05 15:06:59,874:INFO:HR login successful
2021-06-05 15:07:35,698:DEBUG:Using proactor: IocpProactor
2021-06-05 15:07:37,448:INFO:Getting employees details
2021-06-05 15:07:37,480:INFO:Update the employee
2021-06-05 15:07:37,495:INFO:Update the employee
2021-06-05 15:07:37,526:INFO:Employee updated successfully
2021-06-05 15:07:37,526:ERROR:Error in updating employee address
2021-06-05 15:07:37,542:ERROR:Error in updating employee name
2021-06-05 15:07:37,573:INFO:Employee registered successfully
2021-06-05 15:07:37,573:ERROR:Error in address
2021-06-05 15:07:37,589:ERROR:Error in name
2021-06-05 15:07:37,589:INFO:Employee updated successfully
2021-06-05 15:07:37,604:ERROR:Error in updating employee address
2021-06-05 15:07:37,620:ERROR:Error in updating employee name
2021-06-05 15:07:37,636:INFO:Getting all employees attendance
2021-06-05 15:07:37,667:INFO:Getting employees attendance
2021-06-05 15:07:37,698:ERROR:Employee login fails
2021-06-05 15:07:37,698:INFO:Employee login successful
2021-06-05 15:07:37,729:ERROR:HR login fails
2021-06-05 15:07:37,729:INFO:HR login successful
2021-06-05 15:10:49,088:DEBUG:Using proactor: IocpProactor
2021-06-05 15:10:50,307:INFO:Getting employees details
2021-06-05 15:10:50,353:INFO:Update the employee
2021-06-05 15:10:50,369:INFO:Update the employee
2021-06-05 15:10:50,385:INFO:Employee updated successfully
2021-06-05 15:10:50,400:ERROR:Error in updating employee address
2021-06-05 15:10:50,416:ERROR:Error in updating employee name
2021-06-05 15:10:50,432:INFO:Employee registered successfully
2021-06-05 15:10:50,447:ERROR:Error in address
2021-06-05 15:10:50,447:ERROR:Error in name
2021-06-05 15:10:50,463:INFO:Employee updated successfully
2021-06-05 15:10:50,478:ERROR:Error in updating employee address
2021-06-05 15:10:50,494:ERROR:Error in updating employee name
2021-06-05 15:10:50,510:INFO:Getting all employees attendance
2021-06-05 15:10:50,525:INFO:Getting employees attendance
2021-06-05 15:10:50,541:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendence.DoesNotExist: dailyAttendence matching query does not exist.
2021-06-05 15:10:50,619:ERROR:Employee login fails
2021-06-05 15:10:50,635:INFO:Employee login successful
2021-06-05 15:10:50,650:ERROR:HR login fails
2021-06-05 15:10:50,650:INFO:HR login successful
2021-06-05 15:13:50,736:DEBUG:Using proactor: IocpProactor
2021-06-05 15:13:52,142:INFO:Getting employees details
2021-06-05 15:13:52,221:INFO:Update the employee
2021-06-05 15:13:52,252:INFO:Update the employee
2021-06-05 15:13:52,283:INFO:Employee updated successfully
2021-06-05 15:13:52,314:ERROR:Error in updating employee address
2021-06-05 15:13:52,346:ERROR:Error in updating employee name
2021-06-05 15:13:52,392:INFO:Employee registered successfully
2021-06-05 15:13:52,408:ERROR:Error in address
2021-06-05 15:13:52,424:ERROR:Error in name
2021-06-05 15:13:52,439:INFO:Employee updated successfully
2021-06-05 15:13:52,455:ERROR:Error in updating employee address
2021-06-05 15:13:52,470:ERROR:Error in updating employee name
2021-06-05 15:13:52,486:INFO:Getting all employees attendance
2021-06-05 15:13:52,502:INFO:Getting employees attendance
2021-06-05 15:13:52,517:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendence.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendence.DoesNotExist: dailyAttendence matching query does not exist.
2021-06-05 15:13:52,595:ERROR:Employee login fails
2021-06-05 15:13:52,627:INFO:Employee login successful
2021-06-05 15:13:52,674:ERROR:HR login fails
2021-06-05 15:13:52,689:INFO:HR login successful
2021-06-05 15:20:02,223:DEBUG:Using proactor: IocpProactor
2021-06-05 15:20:33,586:DEBUG:Using proactor: IocpProactor
2021-06-05 15:20:39,601:DEBUG:Using proactor: IocpProactor
2021-06-05 15:20:40,898:INFO:Getting employees details
2021-06-05 15:20:40,960:INFO:Update the employee
2021-06-05 15:20:40,976:INFO:Update the employee
2021-06-05 15:20:40,992:INFO:Employee updated successfully
2021-06-05 15:20:41,007:ERROR:Error in updating employee address
2021-06-05 15:20:41,023:ERROR:Error in updating employee name
2021-06-05 15:20:41,039:INFO:Employee registered successfully
2021-06-05 15:20:41,054:ERROR:Error in address
2021-06-05 15:20:41,054:ERROR:Error in name
2021-06-05 15:20:41,070:INFO:Employee updated successfully
2021-06-05 15:20:41,664:ERROR:Error in updating employee address
2021-06-05 15:20:41,882:ERROR:Error in updating employee name
2021-06-05 15:21:56,894:DEBUG:Using proactor: IocpProactor
2021-06-05 15:21:58,365:INFO:Getting employees details
2021-06-05 15:21:58,409:INFO:Update the employee
2021-06-05 15:21:58,425:INFO:Update the employee
2021-06-05 15:21:58,441:INFO:Employee updated successfully
2021-06-05 15:21:58,449:ERROR:Error in updating employee address
2021-06-05 15:21:58,462:ERROR:Error in updating employee name
2021-06-05 15:21:58,486:INFO:Employee registered successfully
2021-06-05 15:21:58,494:ERROR:Error in address
2021-06-05 15:21:58,502:ERROR:Error in name
2021-06-05 15:21:58,518:INFO:Employee updated successfully
2021-06-05 15:21:58,526:ERROR:Error in updating employee address
2021-06-05 15:21:58,534:ERROR:Error in updating employee name
2021-06-05 15:21:58,558:INFO:Getting all employees attendance
2021-06-05 15:21:58,580:INFO:Getting employees attendance
2021-06-05 15:21:58,596:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendance.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendance.DoesNotExist: dailyAttendance matching query does not exist.
2021-06-05 15:21:58,686:ERROR:Employee login fails
2021-06-05 15:21:58,686:INFO:Employee login successful
2021-06-05 15:21:58,717:ERROR:HR login fails
2021-06-05 15:21:58,717:INFO:HR login successful
2021-06-05 15:26:02,183:DEBUG:Using proactor: IocpProactor
2021-06-05 15:26:03,558:INFO:Getting employees details
2021-06-05 15:26:03,589:INFO:Update the employee
2021-06-05 15:26:03,621:INFO:Update the employee
2021-06-05 15:26:03,636:INFO:Employee updated successfully
2021-06-05 15:26:03,636:ERROR:Error in updating employee address
2021-06-05 15:26:03,652:ERROR:Error in updating employee name
2021-06-05 15:26:03,683:INFO:Employee registered successfully
2021-06-05 15:26:03,683:ERROR:Error in address
2021-06-05 15:26:03,699:ERROR:Error in name
2021-06-05 15:26:03,699:INFO:Employee updated successfully
2021-06-05 15:26:03,714:ERROR:Error in updating employee address
2021-06-05 15:26:03,730:ERROR:Error in updating employee name
2021-06-05 15:26:03,746:INFO:Getting all employees attendance
2021-06-05 15:26:03,777:INFO:Getting employees attendance
2021-06-05 15:26:03,792:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 115, in attendanceIn
    emp = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 15:26:03,917:ERROR:Employee login fails
2021-06-05 15:26:03,933:INFO:Employee login successful
2021-06-05 15:26:03,949:ERROR:HR login fails
2021-06-05 15:26:03,949:INFO:HR login successful
2021-06-05 15:33:44,549:DEBUG:Using proactor: IocpProactor
2021-06-05 15:33:45,720:INFO:Getting employees details
2021-06-05 15:33:45,752:INFO:Update the employee
2021-06-05 15:33:45,767:INFO:Update the employee
2021-06-05 15:33:45,783:INFO:Employee updated successfully
2021-06-05 15:33:45,799:ERROR:Error in updating employee address
2021-06-05 15:33:45,814:ERROR:Error in updating employee name
2021-06-05 15:33:45,830:INFO:Employee registered successfully
2021-06-05 15:33:45,845:ERROR:Error in address
2021-06-05 15:33:45,845:ERROR:Error in name
2021-06-05 15:33:45,861:INFO:Employee updated successfully
2021-06-05 15:33:45,877:ERROR:Error in updating employee address
2021-06-05 15:33:45,892:ERROR:Error in updating employee name
2021-06-05 15:33:45,908:INFO:Getting all employees attendance
2021-06-05 15:33:45,924:INFO:Getting employees attendance
2021-06-05 15:33:45,955:INFO:HR/employee session ends
2021-06-05 15:33:45,970:ERROR:Employee login fails
2021-06-05 15:33:45,986:INFO:Employee login successful
2021-06-05 15:33:46,002:ERROR:HR login fails
2021-06-05 15:33:46,002:INFO:HR login successful
2021-06-05 15:34:29,148:DEBUG:Using proactor: IocpProactor
2021-06-05 15:34:30,413:INFO:Getting employees details
2021-06-05 15:34:30,445:INFO:Update the employee
2021-06-05 15:34:30,460:INFO:Update the employee
2021-06-05 15:34:30,476:INFO:Employee updated successfully
2021-06-05 15:34:30,491:ERROR:Error in updating employee address
2021-06-05 15:34:30,507:ERROR:Error in updating employee name
2021-06-05 15:34:30,523:INFO:Employee registered successfully
2021-06-05 15:34:30,538:ERROR:Error in address
2021-06-05 15:34:30,538:ERROR:Error in name
2021-06-05 15:34:30,554:INFO:Employee updated successfully
2021-06-05 15:34:30,569:ERROR:Error in updating employee address
2021-06-05 15:34:30,569:ERROR:Error in updating employee name
2021-06-05 15:34:30,601:INFO:Getting all employees attendance
2021-06-05 15:34:30,616:INFO:Getting employees attendance
2021-06-05 15:34:30,632:INFO:HR/employee session ends
2021-06-05 15:34:30,663:ERROR:Employee login fails
2021-06-05 15:34:30,663:INFO:Employee login successful
2021-06-05 15:34:30,694:ERROR:HR login fails
2021-06-05 15:34:30,694:INFO:HR login successful
2021-06-05 15:36:17,036:DEBUG:Using proactor: IocpProactor
2021-06-05 15:36:18,364:INFO:Getting employees details
2021-06-05 15:36:18,411:INFO:Update the employee
2021-06-05 15:36:18,426:INFO:Update the employee
2021-06-05 15:36:18,442:INFO:Employee updated successfully
2021-06-05 15:36:18,458:ERROR:Error in updating employee address
2021-06-05 15:36:18,473:ERROR:Error in updating employee name
2021-06-05 15:36:18,504:INFO:Employee registered successfully
2021-06-05 15:36:18,520:ERROR:Error in address
2021-06-05 15:36:18,520:ERROR:Error in name
2021-06-05 15:36:18,536:INFO:Employee updated successfully
2021-06-05 15:36:18,551:ERROR:Error in updating employee address
2021-06-05 15:36:18,567:ERROR:Error in updating employee name
2021-06-05 15:36:18,583:INFO:Getting all employees attendance
2021-06-05 15:36:18,614:INFO:Getting employees attendance
2021-06-05 15:36:18,629:WARNING:Wrong session
2021-06-05 15:36:18,661:ERROR:Employee login fails
2021-06-05 15:36:18,661:INFO:Employee login successful
2021-06-05 15:36:18,676:ERROR:HR login fails
2021-06-05 15:36:18,692:INFO:HR login successful
2021-06-05 15:37:05,225:DEBUG:Using proactor: IocpProactor
2021-06-05 15:37:06,974:INFO:Getting employees details
2021-06-05 15:37:07,021:INFO:Update the employee
2021-06-05 15:37:07,036:INFO:Update the employee
2021-06-05 15:37:07,052:INFO:Employee updated successfully
2021-06-05 15:37:07,068:ERROR:Error in updating employee address
2021-06-05 15:37:07,083:ERROR:Error in updating employee name
2021-06-05 15:37:07,099:INFO:Employee registered successfully
2021-06-05 15:37:07,099:ERROR:Error in address
2021-06-05 15:37:07,115:ERROR:Error in name
2021-06-05 15:37:07,146:INFO:Employee updated successfully
2021-06-05 15:37:07,146:ERROR:Error in updating employee address
2021-06-05 15:37:07,161:ERROR:Error in updating employee name
2021-06-05 15:37:07,193:INFO:Getting all employees attendance
2021-06-05 15:37:07,255:INFO:Getting employees attendance
2021-06-05 15:37:07,333:WARNING:Wrong session
2021-06-05 15:37:07,365:ERROR:Employee login fails
2021-06-05 15:37:07,380:INFO:Employee login successful
2021-06-05 15:37:07,396:ERROR:HR login fails
2021-06-05 15:37:07,411:INFO:HR login successful
2021-06-05 15:37:38,599:DEBUG:Using proactor: IocpProactor
2021-06-05 15:37:39,787:INFO:Getting employees details
2021-06-05 15:37:39,834:INFO:Update the employee
2021-06-05 15:37:39,849:INFO:Update the employee
2021-06-05 15:37:39,865:INFO:Employee updated successfully
2021-06-05 15:37:39,880:ERROR:Error in updating employee address
2021-06-05 15:37:39,896:ERROR:Error in updating employee name
2021-06-05 15:37:39,912:INFO:Employee registered successfully
2021-06-05 15:37:39,927:ERROR:Error in address
2021-06-05 15:37:39,927:ERROR:Error in name
2021-06-05 15:37:39,943:INFO:Employee updated successfully
2021-06-05 15:37:39,959:ERROR:Error in updating employee address
2021-06-05 15:37:39,959:ERROR:Error in updating employee name
2021-06-05 15:37:39,990:INFO:Getting all employees attendance
2021-06-05 15:37:40,005:INFO:Getting employees attendance
2021-06-05 15:37:40,037:WARNING:Wrong session
2021-06-05 15:37:40,052:ERROR:Employee login fails
2021-06-05 15:37:40,068:INFO:Employee login successful
2021-06-05 15:37:40,084:ERROR:HR login fails
2021-06-05 15:37:40,084:INFO:HR login successful
2021-06-05 15:42:12,166:DEBUG:Using proactor: IocpProactor
2021-06-05 15:42:13,666:INFO:Getting employees details
2021-06-05 15:42:13,713:INFO:Update the employee
2021-06-05 15:42:13,728:INFO:Update the employee
2021-06-05 15:42:13,744:INFO:Employee updated successfully
2021-06-05 15:42:13,760:ERROR:Error in updating employee address
2021-06-05 15:42:13,760:ERROR:Error in updating employee name
2021-06-05 15:42:13,791:INFO:Employee registered successfully
2021-06-05 15:42:13,791:ERROR:Error in address
2021-06-05 15:42:13,807:ERROR:Error in name
2021-06-05 15:42:13,822:INFO:Employee updated successfully
2021-06-05 15:42:13,822:ERROR:Error in updating employee address
2021-06-05 15:42:13,838:ERROR:Error in updating employee name
2021-06-05 15:42:13,869:INFO:Getting all employees attendance
2021-06-05 15:42:13,885:INFO:Getting employees attendance
2021-06-05 15:42:13,916:WARNING:Wrong session
2021-06-05 15:42:13,932:ERROR:Employee login fails
2021-06-05 15:42:13,947:INFO:Employee login successful
2021-06-05 15:42:13,963:ERROR:HR login fails
2021-06-05 15:42:13,978:INFO:HR login successful
2021-06-05 15:42:38,399:DEBUG:Using proactor: IocpProactor
2021-06-05 15:42:39,805:INFO:Getting employees details
2021-06-05 15:42:39,852:INFO:Update the employee
2021-06-05 15:42:39,883:INFO:Update the employee
2021-06-05 15:42:39,898:INFO:Employee updated successfully
2021-06-05 15:42:39,914:ERROR:Error in updating employee address
2021-06-05 15:42:39,930:ERROR:Error in updating employee name
2021-06-05 15:42:39,961:INFO:Employee registered successfully
2021-06-05 15:42:39,961:ERROR:Error in address
2021-06-05 15:42:39,977:ERROR:Error in name
2021-06-05 15:42:39,992:INFO:Employee updated successfully
2021-06-05 15:42:39,992:ERROR:Error in updating employee address
2021-06-05 15:42:40,008:ERROR:Error in updating employee name
2021-06-05 15:42:40,039:INFO:Getting all employees attendance
2021-06-05 15:42:40,055:INFO:Getting employees attendance
2021-06-05 15:42:40,070:WARNING:Wrong session
2021-06-05 15:42:40,102:ERROR:Employee login fails
2021-06-05 15:42:40,117:INFO:Employee login successful
2021-06-05 15:42:40,133:ERROR:HR login fails
2021-06-05 15:42:40,133:INFO:HR login successful
2021-06-05 15:43:04,022:DEBUG:Using proactor: IocpProactor
2021-06-05 15:43:05,334:INFO:Getting employees details
2021-06-05 15:43:05,381:INFO:Update the employee
2021-06-05 15:43:05,397:INFO:Update the employee
2021-06-05 15:43:05,412:INFO:Employee updated successfully
2021-06-05 15:43:05,428:ERROR:Error in updating employee address
2021-06-05 15:43:05,443:ERROR:Error in updating employee name
2021-06-05 15:43:05,459:INFO:Employee registered successfully
2021-06-05 15:43:05,459:ERROR:Error in address
2021-06-05 15:43:05,475:ERROR:Error in name
2021-06-05 15:43:05,490:INFO:Employee updated successfully
2021-06-05 15:43:05,490:ERROR:Error in updating employee address
2021-06-05 15:43:05,506:ERROR:Error in updating employee name
2021-06-05 15:43:05,522:INFO:Getting all employees attendance
2021-06-05 15:43:05,553:INFO:Getting employees attendance
2021-06-05 15:43:05,568:WARNING:Wrong session
2021-06-05 15:43:05,600:ERROR:Employee login fails
2021-06-05 15:43:05,615:INFO:Employee login successful
2021-06-05 15:43:05,631:ERROR:HR login fails
2021-06-05 15:43:05,647:INFO:HR login successful
2021-06-05 15:45:33,606:DEBUG:Using proactor: IocpProactor
2021-06-05 15:45:35,356:INFO:Getting employees details
2021-06-05 15:45:35,418:INFO:Update the employee
2021-06-05 15:45:35,434:INFO:Update the employee
2021-06-05 15:45:35,450:INFO:Employee updated successfully
2021-06-05 15:45:35,465:ERROR:Error in updating employee address
2021-06-05 15:45:35,481:ERROR:Error in updating employee name
2021-06-05 15:45:35,528:INFO:Employee registered successfully
2021-06-05 15:45:35,543:ERROR:Error in address
2021-06-05 15:45:35,559:ERROR:Error in name
2021-06-05 15:45:35,590:INFO:Employee updated successfully
2021-06-05 15:45:35,606:ERROR:Error in updating employee address
2021-06-05 15:45:35,622:ERROR:Error in updating employee name
2021-06-05 15:45:35,653:INFO:Getting all employees attendance
2021-06-05 15:45:35,700:INFO:Getting employees attendance
2021-06-05 15:45:35,731:WARNING:Wrong session
2021-06-05 15:45:35,762:ERROR:Employee login fails
2021-06-05 15:45:35,778:INFO:Employee login successful
2021-06-05 15:45:35,809:ERROR:HR login fails
2021-06-05 15:45:35,809:INFO:HR login successful
2021-06-05 15:52:09,413:DEBUG:Using proactor: IocpProactor
2021-06-05 15:52:10,960:INFO:Getting employees details
2021-06-05 15:52:11,007:INFO:Update the employee
2021-06-05 15:52:11,038:INFO:Update the employee
2021-06-05 15:52:11,054:INFO:Employee updated successfully
2021-06-05 15:52:11,085:ERROR:Error in updating employee address
2021-06-05 15:52:11,101:ERROR:Error in updating employee name
2021-06-05 15:52:11,132:INFO:Employee registered successfully
2021-06-05 15:52:11,147:ERROR:Error in address
2021-06-05 15:52:11,147:ERROR:Error in name
2021-06-05 15:52:11,179:INFO:Employee updated successfully
2021-06-05 15:52:11,210:ERROR:Error in updating employee address
2021-06-05 15:52:11,226:ERROR:Error in updating employee name
2021-06-05 15:52:11,241:INFO:Getting all employees attendance
2021-06-05 15:52:11,257:INFO:Getting employees attendance
2021-06-05 15:52:11,288:WARNING:Wrong session
2021-06-05 15:52:11,288:ERROR:HR login fails
2021-06-05 15:52:11,304:WARNING:Not Found: /dashboard
2021-06-05 15:52:11,319:ERROR:Employee login fails
2021-06-05 15:52:11,335:INFO:Employee login successful
2021-06-05 15:52:11,351:ERROR:HR login fails
2021-06-05 15:52:11,366:INFO:HR login successful
2021-06-05 15:52:34,177:DEBUG:Using proactor: IocpProactor
2021-06-05 15:52:35,458:INFO:Getting employees details
2021-06-05 15:52:35,489:INFO:Update the employee
2021-06-05 15:52:35,505:INFO:Update the employee
2021-06-05 15:52:35,521:INFO:Employee updated successfully
2021-06-05 15:52:35,536:ERROR:Error in updating employee address
2021-06-05 15:52:35,552:ERROR:Error in updating employee name
2021-06-05 15:52:35,568:INFO:Employee registered successfully
2021-06-05 15:52:35,583:ERROR:Error in address
2021-06-05 15:52:35,583:ERROR:Error in name
2021-06-05 15:52:35,599:INFO:Employee updated successfully
2021-06-05 15:52:35,614:ERROR:Error in updating employee address
2021-06-05 15:52:35,630:ERROR:Error in updating employee name
2021-06-05 15:52:35,646:INFO:Getting all employees attendance
2021-06-05 15:52:35,661:INFO:Getting employees attendance
2021-06-05 15:52:35,693:WARNING:Wrong session
2021-06-05 15:52:35,693:ERROR:HR login fails
2021-06-05 15:52:35,708:WARNING:Not Found: /dashboard
2021-06-05 15:52:35,724:ERROR:Employee login fails
2021-06-05 15:52:35,739:INFO:Employee login successful
2021-06-05 15:52:35,755:ERROR:HR login fails
2021-06-05 15:52:35,755:INFO:HR login successful
2021-06-05 15:52:55,115:DEBUG:Using proactor: IocpProactor
2021-06-05 15:52:56,412:INFO:Getting employees details
2021-06-05 15:52:56,459:INFO:Update the employee
2021-06-05 15:52:56,475:INFO:Update the employee
2021-06-05 15:52:56,490:INFO:Employee updated successfully
2021-06-05 15:52:56,506:ERROR:Error in updating employee address
2021-06-05 15:52:56,522:ERROR:Error in updating employee name
2021-06-05 15:52:56,537:INFO:Employee registered successfully
2021-06-05 15:52:56,537:ERROR:Error in address
2021-06-05 15:52:56,553:ERROR:Error in name
2021-06-05 15:52:56,568:INFO:Employee updated successfully
2021-06-05 15:52:56,568:ERROR:Error in updating employee address
2021-06-05 15:52:56,584:ERROR:Error in updating employee name
2021-06-05 15:52:56,615:INFO:Getting all employees attendance
2021-06-05 15:52:56,631:INFO:Getting employees attendance
2021-06-05 15:52:56,662:WARNING:Wrong session
2021-06-05 15:52:56,662:ERROR:HR login fails
2021-06-05 15:52:56,678:WARNING:Not Found: /dashboard
2021-06-05 15:52:56,693:ERROR:Employee login fails
2021-06-05 15:52:56,709:INFO:Employee login successful
2021-06-05 15:52:56,725:ERROR:HR login fails
2021-06-05 15:52:56,725:INFO:HR login successful
2021-06-05 15:53:44,246:DEBUG:Using proactor: IocpProactor
2021-06-05 15:53:45,746:INFO:Getting employees details
2021-06-05 15:53:45,777:INFO:Update the employee
2021-06-05 15:53:45,792:INFO:Update the employee
2021-06-05 15:53:45,808:INFO:Employee updated successfully
2021-06-05 15:53:45,824:ERROR:Error in updating employee address
2021-06-05 15:53:45,839:ERROR:Error in updating employee name
2021-06-05 15:53:45,871:INFO:Employee registered successfully
2021-06-05 15:53:45,886:ERROR:Error in address
2021-06-05 15:53:45,886:ERROR:Error in name
2021-06-05 15:53:45,902:INFO:Employee updated successfully
2021-06-05 15:53:45,917:ERROR:Error in updating employee address
2021-06-05 15:53:45,917:ERROR:Error in updating employee name
2021-06-05 15:53:45,949:INFO:Getting all employees attendance
2021-06-05 15:53:45,964:INFO:Getting employees attendance
2021-06-05 15:53:45,980:WARNING:Wrong session
2021-06-05 15:53:46,011:ERROR:Employee login fails
2021-06-05 15:53:46,027:INFO:Employee login successful
2021-06-05 15:53:46,042:ERROR:HR login fails
2021-06-05 15:53:46,042:INFO:HR login successful
2021-06-05 15:56:08,703:DEBUG:Using proactor: IocpProactor
2021-06-05 15:56:10,156:INFO:Getting employees details
2021-06-05 15:56:10,202:INFO:Update the employee
2021-06-05 15:56:10,218:INFO:Update the employee
2021-06-05 15:56:10,234:INFO:Employee updated successfully
2021-06-05 15:56:10,234:ERROR:Error in updating employee address
2021-06-05 15:56:10,249:ERROR:Error in updating employee name
2021-06-05 15:56:10,281:INFO:Employee registered successfully
2021-06-05 15:56:10,281:ERROR:Error in address
2021-06-05 15:56:10,296:ERROR:Error in name
2021-06-05 15:56:10,312:INFO:Employee updated successfully
2021-06-05 15:56:10,312:ERROR:Error in updating employee address
2021-06-05 15:56:10,327:ERROR:Error in updating employee name
2021-06-05 15:56:10,343:INFO:Getting all employees attendance
2021-06-05 15:56:10,374:INFO:Getting employees attendance
2021-06-05 15:56:10,390:WARNING:Wrong session
2021-06-05 15:56:10,421:ERROR:Employee login fails
2021-06-05 15:56:10,437:INFO:Employee login successful
2021-06-05 15:56:10,437:ERROR:HR login fails
2021-06-05 15:56:10,452:INFO:HR login successful
2021-06-05 15:56:10,452:INFO:HR/employee session ends
2021-06-05 15:56:23,436:DEBUG:Using proactor: IocpProactor
2021-06-05 15:56:24,748:INFO:Getting employees details
2021-06-05 15:56:24,795:INFO:Update the employee
2021-06-05 15:56:24,811:INFO:Update the employee
2021-06-05 15:56:24,826:INFO:Employee updated successfully
2021-06-05 15:56:24,842:ERROR:Error in updating employee address
2021-06-05 15:56:24,858:ERROR:Error in updating employee name
2021-06-05 15:56:24,873:INFO:Employee registered successfully
2021-06-05 15:56:24,889:ERROR:Error in address
2021-06-05 15:56:24,889:ERROR:Error in name
2021-06-05 15:56:24,905:INFO:Employee updated successfully
2021-06-05 15:56:24,920:ERROR:Error in updating employee address
2021-06-05 15:56:24,920:ERROR:Error in updating employee name
2021-06-05 15:56:24,951:INFO:Getting all employees attendance
2021-06-05 15:56:24,983:INFO:Getting employees attendance
2021-06-05 15:56:24,998:WARNING:Wrong session
2021-06-05 15:56:25,030:ERROR:Employee login fails
2021-06-05 15:56:25,045:INFO:Employee login successful
2021-06-05 15:56:25,061:ERROR:HR login fails
2021-06-05 15:56:25,061:INFO:HR login successful
2021-06-05 15:56:25,076:INFO:HR/employee session ends
2021-06-05 15:56:58,594:DEBUG:Using proactor: IocpProactor
2021-06-05 15:56:59,946:INFO:Getting employees details
2021-06-05 15:56:59,977:INFO:Update the employee
2021-06-05 15:57:00,008:INFO:Update the employee
2021-06-05 15:57:00,024:INFO:Employee updated successfully
2021-06-05 15:57:00,040:ERROR:Error in updating employee address
2021-06-05 15:57:00,055:ERROR:Error in updating employee name
2021-06-05 15:57:00,086:INFO:Employee registered successfully
2021-06-05 15:57:00,086:ERROR:Error in address
2021-06-05 15:57:00,102:ERROR:Error in name
2021-06-05 15:57:00,118:INFO:Employee updated successfully
2021-06-05 15:57:00,118:ERROR:Error in updating employee address
2021-06-05 15:57:00,133:ERROR:Error in updating employee name
2021-06-05 15:57:00,149:INFO:Getting all employees attendance
2021-06-05 15:57:00,196:INFO:Getting employees attendance
2021-06-05 15:57:00,211:WARNING:Wrong session
2021-06-05 15:57:00,243:ERROR:Employee login fails
2021-06-05 15:57:00,243:INFO:Employee login successful
2021-06-05 15:57:00,258:ERROR:HR login fails
2021-06-05 15:57:00,274:INFO:HR login successful
2021-06-05 15:57:00,274:INFO:HR/employee session ends
2021-06-05 15:59:22,712:DEBUG:Using proactor: IocpProactor
2021-06-05 15:59:23,977:INFO:Getting employees details
2021-06-05 15:59:24,024:INFO:Update the employee
2021-06-05 15:59:24,040:INFO:Update the employee
2021-06-05 15:59:24,055:INFO:Employee updated successfully
2021-06-05 15:59:24,071:ERROR:Error in updating employee address
2021-06-05 15:59:24,087:ERROR:Error in updating employee name
2021-06-05 15:59:24,102:INFO:Employee registered successfully
2021-06-05 15:59:24,102:ERROR:Error in address
2021-06-05 15:59:24,118:ERROR:Error in name
2021-06-05 15:59:24,134:INFO:Employee updated successfully
2021-06-05 15:59:24,149:ERROR:Error in updating employee address
2021-06-05 15:59:24,149:ERROR:Error in updating employee name
2021-06-05 15:59:24,180:INFO:Getting all employees attendance
2021-06-05 15:59:24,196:INFO:Getting employees attendance
2021-06-05 15:59:24,212:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 115, in attendanceIn
    emp = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 15:59:24,290:WARNING:Wrong session
2021-06-05 15:59:24,321:ERROR:Employee login fails
2021-06-05 15:59:24,321:INFO:Employee login successful
2021-06-05 15:59:24,337:ERROR:HR login fails
2021-06-05 15:59:24,352:INFO:HR login successful
2021-06-05 15:59:24,352:INFO:HR/employee session ends
2021-06-05 16:02:33,364:DEBUG:Using proactor: IocpProactor
2021-06-05 16:02:34,864:INFO:Getting employees details
2021-06-05 16:02:34,911:INFO:Update the employee
2021-06-05 16:02:34,926:INFO:Update the employee
2021-06-05 16:02:34,942:INFO:Employee updated successfully
2021-06-05 16:02:34,942:ERROR:Error in updating employee address
2021-06-05 16:02:34,957:ERROR:Error in updating employee name
2021-06-05 16:02:34,989:INFO:Employee registered successfully
2021-06-05 16:02:34,989:ERROR:Error in address
2021-06-05 16:02:35,004:ERROR:Error in name
2021-06-05 16:02:35,004:INFO:Employee updated successfully
2021-06-05 16:02:35,020:ERROR:Error in updating employee address
2021-06-05 16:02:35,036:ERROR:Error in updating employee name
2021-06-05 16:02:35,051:INFO:Getting all employees attendance
2021-06-05 16:02:35,082:INFO:Getting employees attendance
2021-06-05 16:02:35,098:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    emp = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 16:02:35,192:WARNING:Wrong session
2021-06-05 16:02:35,207:ERROR:Employee login fails
2021-06-05 16:02:35,223:INFO:Employee login successful
2021-06-05 16:02:35,239:ERROR:HR login fails
2021-06-05 16:02:35,239:INFO:HR login successful
2021-06-05 16:02:35,254:INFO:HR/employee session ends
2021-06-05 16:03:20,197:DEBUG:Using proactor: IocpProactor
2021-06-05 16:03:21,525:INFO:Getting employees details
2021-06-05 16:03:21,556:INFO:Update the employee
2021-06-05 16:03:21,572:INFO:Update the employee
2021-06-05 16:03:21,587:INFO:Employee updated successfully
2021-06-05 16:03:21,603:ERROR:Error in updating employee address
2021-06-05 16:03:21,619:ERROR:Error in updating employee name
2021-06-05 16:03:21,634:INFO:Employee registered successfully
2021-06-05 16:03:21,650:ERROR:Error in address
2021-06-05 16:03:21,650:ERROR:Error in name
2021-06-05 16:03:21,665:INFO:Employee updated successfully
2021-06-05 16:03:21,681:ERROR:Error in updating employee address
2021-06-05 16:03:21,697:ERROR:Error in updating employee name
2021-06-05 16:03:21,712:INFO:Getting all employees attendance
2021-06-05 16:03:21,728:INFO:Getting employees attendance
2021-06-05 16:03:21,759:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 117, in attendanceIn
    daily = dailyAttendance.objects.get(empId=empId)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendance.DoesNotExist: dailyAttendance matching query does not exist.
2021-06-05 16:03:21,822:WARNING:Wrong session
2021-06-05 16:03:21,837:ERROR:Employee login fails
2021-06-05 16:03:21,853:INFO:Employee login successful
2021-06-05 16:03:21,869:ERROR:HR login fails
2021-06-05 16:03:21,869:INFO:HR login successful
2021-06-05 16:03:21,884:INFO:HR/employee session ends
2021-06-05 16:03:56,995:DEBUG:Using proactor: IocpProactor
2021-06-05 16:03:58,260:INFO:Getting employees details
2021-06-05 16:03:58,307:INFO:Update the employee
2021-06-05 16:03:58,332:INFO:Update the employee
2021-06-05 16:03:58,348:INFO:Employee updated successfully
2021-06-05 16:03:58,364:ERROR:Error in updating employee address
2021-06-05 16:03:58,372:ERROR:Error in updating employee name
2021-06-05 16:03:58,396:INFO:Employee registered successfully
2021-06-05 16:03:58,404:ERROR:Error in address
2021-06-05 16:03:58,412:ERROR:Error in name
2021-06-05 16:03:58,428:INFO:Employee updated successfully
2021-06-05 16:03:58,436:ERROR:Error in updating employee address
2021-06-05 16:03:58,444:ERROR:Error in updating employee name
2021-06-05 16:03:58,468:INFO:Getting all employees attendance
2021-06-05 16:03:58,492:INFO:Getting employees attendance
2021-06-05 16:03:58,508:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 117, in attendanceIn
    daily = dailyAttendance.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 16:03:58,621:WARNING:Wrong session
2021-06-05 16:03:58,652:ERROR:Employee login fails
2021-06-05 16:03:58,667:INFO:Employee login successful
2021-06-05 16:03:58,667:ERROR:HR login fails
2021-06-05 16:03:58,683:INFO:HR login successful
2021-06-05 16:03:58,699:INFO:HR/employee session ends
2021-06-05 16:05:03,359:DEBUG:Using proactor: IocpProactor
2021-06-05 16:05:04,625:INFO:Getting employees details
2021-06-05 16:05:04,672:INFO:Update the employee
2021-06-05 16:05:04,687:INFO:Update the employee
2021-06-05 16:05:04,703:INFO:Employee updated successfully
2021-06-05 16:05:04,719:ERROR:Error in updating employee address
2021-06-05 16:05:04,719:ERROR:Error in updating employee name
2021-06-05 16:05:04,750:INFO:Employee registered successfully
2021-06-05 16:05:04,766:ERROR:Error in address
2021-06-05 16:05:04,766:ERROR:Error in name
2021-06-05 16:05:04,781:INFO:Employee updated successfully
2021-06-05 16:05:04,797:ERROR:Error in updating employee address
2021-06-05 16:05:04,812:ERROR:Error in updating employee name
2021-06-05 16:05:04,828:INFO:Getting all employees attendance
2021-06-05 16:05:04,844:INFO:Getting employees attendance
2021-06-05 16:05:04,859:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'empTable object (2)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 115, in attendanceIn
    emp = empTable.objects.get(id=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'empTable object (2)'.
2021-06-05 16:05:04,953:WARNING:Wrong session
2021-06-05 16:05:04,969:ERROR:Employee login fails
2021-06-05 16:05:04,984:INFO:Employee login successful
2021-06-05 16:05:05,000:ERROR:HR login fails
2021-06-05 16:05:05,016:INFO:HR login successful
2021-06-05 16:05:05,016:INFO:HR/employee session ends
2021-06-05 16:05:52,747:DEBUG:Using proactor: IocpProactor
2021-06-05 16:05:54,418:INFO:Getting employees details
2021-06-05 16:05:54,450:INFO:Update the employee
2021-06-05 16:05:54,465:INFO:Update the employee
2021-06-05 16:05:54,481:INFO:Employee updated successfully
2021-06-05 16:05:54,496:ERROR:Error in updating employee address
2021-06-05 16:05:54,512:ERROR:Error in updating employee name
2021-06-05 16:05:54,528:INFO:Employee registered successfully
2021-06-05 16:05:54,543:ERROR:Error in address
2021-06-05 16:05:54,543:ERROR:Error in name
2021-06-05 16:05:54,559:INFO:Employee updated successfully
2021-06-05 16:05:54,575:ERROR:Error in updating employee address
2021-06-05 16:05:54,590:ERROR:Error in updating employee name
2021-06-05 16:05:54,606:INFO:Getting all employees attendance
2021-06-05 16:05:54,637:INFO:Getting employees attendance
2021-06-05 16:05:54,653:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 116, in attendanceIn
    daily = dailyAttendance.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.dailyAttendance.DoesNotExist: dailyAttendance matching query does not exist.
2021-06-05 16:05:54,715:WARNING:Wrong session
2021-06-05 16:05:54,731:ERROR:Employee login fails
2021-06-05 16:05:54,746:INFO:Employee login successful
2021-06-05 16:05:54,762:ERROR:HR login fails
2021-06-05 16:05:54,778:INFO:HR login successful
2021-06-05 16:05:54,778:INFO:HR/employee session ends
2021-06-05 16:08:12,381:DEBUG:Using proactor: IocpProactor
2021-06-05 16:08:13,896:INFO:Getting employees details
2021-06-05 16:08:13,943:INFO:Update the employee
2021-06-05 16:08:13,959:INFO:Update the employee
2021-06-05 16:08:13,974:INFO:Employee updated successfully
2021-06-05 16:08:13,990:ERROR:Error in updating employee address
2021-06-05 16:08:14,005:ERROR:Error in updating employee name
2021-06-05 16:08:14,021:INFO:Employee registered successfully
2021-06-05 16:08:14,037:ERROR:Error in address
2021-06-05 16:08:14,037:ERROR:Error in name
2021-06-05 16:08:14,052:INFO:Employee updated successfully
2021-06-05 16:08:14,068:ERROR:Error in updating employee address
2021-06-05 16:08:14,068:ERROR:Error in updating employee name
2021-06-05 16:08:14,099:INFO:Getting all employees attendance
2021-06-05 16:08:14,115:INFO:Getting employees attendance
2021-06-05 16:08:14,162:WARNING:Wrong session
2021-06-05 16:08:14,177:ERROR:Employee login fails
2021-06-05 16:08:14,193:INFO:Employee login successful
2021-06-05 16:08:14,209:ERROR:HR login fails
2021-06-05 16:08:14,224:INFO:HR login successful
2021-06-05 16:08:14,224:INFO:HR/employee session ends
2021-06-05 16:10:29,885:DEBUG:Using proactor: IocpProactor
2021-06-05 16:10:31,260:INFO:Getting employees details
2021-06-05 16:10:31,307:INFO:Update the employee
2021-06-05 16:10:31,322:INFO:Update the employee
2021-06-05 16:10:31,338:INFO:Employee updated successfully
2021-06-05 16:10:31,354:ERROR:Error in updating employee address
2021-06-05 16:10:31,369:ERROR:Error in updating employee name
2021-06-05 16:10:31,400:INFO:Employee registered successfully
2021-06-05 16:10:31,400:ERROR:Error in address
2021-06-05 16:10:31,416:ERROR:Error in name
2021-06-05 16:10:31,432:INFO:Employee updated successfully
2021-06-05 16:10:31,447:ERROR:Error in updating employee address
2021-06-05 16:10:31,463:ERROR:Error in updating employee name
2021-06-05 16:10:31,478:INFO:Getting all employees attendance
2021-06-05 16:10:31,510:INFO:Getting employees attendance
2021-06-05 16:10:31,557:ERROR:Internal Server Error: /attendanceIn
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 117, in attendanceIn
    inTime = request.POST['in']
  File "c:\users\kanis\envs\test\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'in'
2021-06-05 16:10:31,619:WARNING:Wrong session
2021-06-05 16:10:31,650:ERROR:Employee login fails
2021-06-05 16:10:31,666:INFO:Employee login successful
2021-06-05 16:10:31,682:ERROR:HR login fails
2021-06-05 16:10:31,682:INFO:HR login successful
2021-06-05 16:10:31,697:INFO:HR/employee session ends
2021-06-05 16:11:00,165:DEBUG:Using proactor: IocpProactor
2021-06-05 16:11:01,571:INFO:Getting employees details
2021-06-05 16:11:01,603:INFO:Update the employee
2021-06-05 16:11:01,634:INFO:Update the employee
2021-06-05 16:11:01,650:INFO:Employee updated successfully
2021-06-05 16:11:01,681:ERROR:Error in updating employee address
2021-06-05 16:11:01,681:ERROR:Error in updating employee name
2021-06-05 16:11:01,712:INFO:Employee registered successfully
2021-06-05 16:11:01,712:ERROR:Error in address
2021-06-05 16:11:01,728:ERROR:Error in name
2021-06-05 16:11:01,743:INFO:Employee updated successfully
2021-06-05 16:11:01,743:ERROR:Error in updating employee address
2021-06-05 16:11:01,759:ERROR:Error in updating employee name
2021-06-05 16:11:01,775:INFO:Getting all employees attendance
2021-06-05 16:11:01,806:INFO:Getting employees attendance
2021-06-05 16:11:01,853:WARNING:Wrong session
2021-06-05 16:11:01,884:ERROR:Employee login fails
2021-06-05 16:11:01,900:INFO:Employee login successful
2021-06-05 16:11:01,900:ERROR:HR login fails
2021-06-05 16:11:01,915:INFO:HR login successful
2021-06-05 16:11:01,931:INFO:HR/employee session ends
2021-06-05 16:13:07,606:DEBUG:Using proactor: IocpProactor
2021-06-05 16:13:08,825:INFO:Getting employees details
2021-06-05 16:13:08,856:INFO:Update the employee
2021-06-05 16:13:08,887:INFO:Update the employee
2021-06-05 16:13:08,887:INFO:Employee updated successfully
2021-06-05 16:13:08,903:ERROR:Error in updating employee address
2021-06-05 16:13:08,934:ERROR:Error in updating employee name
2021-06-05 16:13:08,981:INFO:Employee registered successfully
2021-06-05 16:13:08,997:ERROR:Error in address
2021-06-05 16:13:09,012:ERROR:Error in name
2021-06-05 16:13:09,044:INFO:Employee updated successfully
2021-06-05 16:13:09,059:ERROR:Error in updating employee address
2021-06-05 16:13:09,090:ERROR:Error in updating employee name
2021-06-05 16:13:09,137:INFO:Getting all employees attendance
2021-06-05 16:13:09,200:INFO:Getting employees attendance
2021-06-05 16:13:09,278:ERROR:Internal Server Error: /attendanceOut
Traceback (most recent call last):
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\kanis\envs\test\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanis\projects\HR\Management\views.py", line 142, in attendanceOut
    empAtt = empAttendance.objects.get(empId=id2)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\kanis\envs\test\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
Management.models.empAttendance.DoesNotExist: empAttendance matching query does not exist.
2021-06-05 16:13:09,418:WARNING:Wrong session
2021-06-05 16:13:09,465:ERROR:Employee login fails
2021-06-05 16:13:09,497:INFO:Employee login successful
2021-06-05 16:13:09,543:ERROR:HR login fails
2021-06-05 16:13:09,559:INFO:HR login successful
2021-06-05 16:13:09,575:INFO:HR/employee session ends
2021-06-05 16:15:24,602:DEBUG:Using proactor: IocpProactor
2021-06-05 16:15:25,945:INFO:Getting employees details
2021-06-05 16:15:25,992:INFO:Update the employee
2021-06-05 16:15:26,008:INFO:Update the employee
2021-06-05 16:15:26,023:INFO:Employee updated successfully
2021-06-05 16:15:26,039:ERROR:Error in updating employee address
2021-06-05 16:15:26,055:ERROR:Error in updating employee name
2021-06-05 16:15:26,070:INFO:Employee registered successfully
2021-06-05 16:15:26,070:ERROR:Error in address
2021-06-05 16:15:26,086:ERROR:Error in name
2021-06-05 16:15:26,101:INFO:Employee updated successfully
2021-06-05 16:15:26,101:ERROR:Error in updating employee address
2021-06-05 16:15:26,117:ERROR:Error in updating employee name
2021-06-05 16:15:26,133:INFO:Getting all employees attendance
2021-06-05 16:15:26,164:INFO:Getting employees attendance
2021-06-05 16:15:26,226:WARNING:Wrong session
2021-06-05 16:15:26,242:ERROR:Employee login fails
2021-06-05 16:15:26,258:INFO:Employee login successful
2021-06-05 16:15:26,273:ERROR:HR login fails
2021-06-05 16:15:26,289:INFO:HR login successful
2021-06-05 16:15:26,289:INFO:HR/employee session ends
2021-06-05 16:17:31,341:DEBUG:Using proactor: IocpProactor
2021-06-05 16:17:32,810:INFO:Getting employees details
2021-06-05 16:17:32,841:INFO:Update the employee
2021-06-05 16:17:32,857:INFO:Update the employee
2021-06-05 16:17:32,872:INFO:Employee updated successfully
2021-06-05 16:17:32,888:ERROR:Error in updating employee address
2021-06-05 16:17:32,904:ERROR:Error in updating employee name
2021-06-05 16:17:32,919:INFO:Employee registered successfully
2021-06-05 16:17:32,935:ERROR:Error in address
2021-06-05 16:17:32,935:ERROR:Error in name
2021-06-05 16:17:32,951:INFO:Employee updated successfully
2021-06-05 16:17:32,966:ERROR:Error in updating employee address
2021-06-05 16:17:32,966:ERROR:Error in updating employee name
2021-06-05 16:17:32,997:INFO:Getting all employees attendance
2021-06-05 16:17:33,013:INFO:Getting employees attendance
2021-06-05 16:17:33,076:WARNING:Wrong session
2021-06-05 16:17:33,107:ERROR:Employee login fails
2021-06-05 16:17:33,122:INFO:Employee login successful
2021-06-05 16:17:33,154:ERROR:HR login fails
2021-06-05 16:17:33,154:INFO:HR login successful
2021-06-05 16:17:33,154:INFO:HR/employee session ends
2021-06-10 15:24:13,146:INFO:Getting employees details
2021-06-10 15:24:13,333:INFO:Update the employee
2021-06-10 15:24:13,364:INFO:Update the employee
2021-06-10 15:24:13,396:INFO:Employee updated successfully
2021-06-10 15:24:13,411:ERROR:Error in updating employee address
2021-06-10 15:24:13,427:ERROR:Error in updating employee name
2021-06-10 15:24:13,458:INFO:Employee registered successfully
2021-06-10 15:24:13,458:ERROR:Error in address
2021-06-10 15:24:13,474:ERROR:Error in name
2021-06-10 15:24:13,489:INFO:Employee updated successfully
2021-06-10 15:24:13,505:ERROR:Error in updating employee address
2021-06-10 15:24:13,536:ERROR:Error in updating employee name
2021-06-10 15:24:13,583:INFO:Getting all employees attendance
2021-06-10 15:24:13,661:INFO:Getting employees attendance
2021-06-10 15:24:13,771:WARNING:Wrong session
2021-06-10 15:24:13,802:ERROR:Employee login fails
2021-06-10 15:24:13,817:INFO:Employee login successful
2021-06-10 15:24:13,833:ERROR:HR login fails
2021-06-10 15:24:13,849:INFO:HR login successful
2021-06-10 15:24:13,849:INFO:HR/employee session ends
2021-06-10 15:27:29,024:INFO:Getting employees details
2021-06-10 15:27:29,070:INFO:Update the employee
2021-06-10 15:27:29,086:INFO:Update the employee
2021-06-10 15:27:29,086:INFO:Employee updated successfully
2021-06-10 15:27:29,102:ERROR:Error in updating employee address
2021-06-10 15:27:29,117:ERROR:Error in updating employee name
2021-06-10 15:27:29,133:INFO:Employee registered successfully
2021-06-10 15:27:29,133:ERROR:Error in address
2021-06-10 15:27:29,149:ERROR:Error in name
2021-06-10 15:27:29,149:INFO:Employee updated successfully
2021-06-10 15:27:29,164:ERROR:Error in updating employee address
2021-06-10 15:27:29,164:ERROR:Error in updating employee name
2021-06-10 15:27:29,180:INFO:Getting all employees attendance
2021-06-10 15:27:29,211:INFO:Getting employees attendance
2021-06-10 15:27:29,258:WARNING:Wrong session
2021-06-10 15:27:29,274:ERROR:Employee login fails
2021-06-10 15:27:29,289:INFO:Employee login successful
2021-06-10 15:27:29,305:ERROR:HR login fails
2021-06-10 15:27:29,305:INFO:HR login successful
2021-06-10 15:27:29,320:INFO:HR/employee session ends
2021-06-10 15:28:46,088:INFO:Getting employees details
2021-06-10 15:28:46,135:INFO:Update the employee
2021-06-10 15:28:46,167:INFO:Update the employee
2021-06-10 15:28:46,182:INFO:Employee updated successfully
2021-06-10 15:28:46,198:ERROR:Error in updating employee address
2021-06-10 15:28:46,198:ERROR:Error in updating employee name
2021-06-10 15:28:46,213:INFO:Employee registered successfully
2021-06-10 15:28:46,229:ERROR:Error in address
2021-06-10 15:28:46,229:ERROR:Error in name
2021-06-10 15:28:46,245:INFO:Employee updated successfully
2021-06-10 15:28:46,245:ERROR:Error in updating employee address
2021-06-10 15:28:46,260:ERROR:Error in updating employee name
2021-06-10 15:28:46,276:INFO:Getting all employees attendance
2021-06-10 15:28:46,291:INFO:Getting employees attendance
2021-06-10 15:28:46,338:WARNING:Wrong session
2021-06-10 15:28:46,370:ERROR:Employee login fails
2021-06-10 15:28:46,370:INFO:Employee login successful
2021-06-10 15:28:46,385:ERROR:HR login fails
2021-06-10 15:28:46,401:INFO:HR login successful
2021-06-10 15:28:46,401:INFO:HR/employee session ends
2021-06-10 15:29:50,285:INFO:Getting employees details
2021-06-10 15:29:50,347:INFO:Update the employee
2021-06-10 15:29:50,410:INFO:Update the employee
2021-06-10 15:29:50,457:INFO:Employee updated successfully
2021-06-10 15:29:50,503:ERROR:Error in updating employee address
2021-06-10 15:29:50,519:ERROR:Error in updating employee name
2021-06-10 15:29:50,550:INFO:Employee registered successfully
2021-06-10 15:29:50,566:ERROR:Error in address
2021-06-10 15:29:50,582:ERROR:Error in name
2021-06-10 15:29:50,597:INFO:Employee updated successfully
2021-06-10 15:29:50,597:ERROR:Error in updating employee address
2021-06-10 15:29:50,628:ERROR:Error in updating employee name
2021-06-10 15:29:50,644:INFO:Getting all employees attendance
2021-06-10 15:29:50,675:INFO:Getting employees attendance
2021-06-10 15:29:50,753:WARNING:Wrong session
2021-06-10 15:29:50,769:ERROR:Employee login fails
2021-06-10 15:29:50,800:INFO:Employee login successful
2021-06-10 15:29:50,816:ERROR:HR login fails
2021-06-10 15:29:50,816:INFO:HR login successful
2021-06-10 15:29:50,832:INFO:HR/employee session ends
2021-06-10 16:39:36,490:WARNING:Not Found: /favicon.ico
2021-06-10 16:39:42,853:DEBUG:Using proactor: IocpProactor
2021-06-10 16:48:18,848:INFO:Getting employees details
2021-06-10 16:48:18,899:INFO:Update the employee
2021-06-10 16:48:18,923:INFO:Update the employee
2021-06-10 16:48:18,939:INFO:Employee updated successfully
2021-06-10 16:48:18,955:ERROR:Error in updating employee address
2021-06-10 16:48:18,971:ERROR:Error in updating employee name
2021-06-10 16:48:19,011:INFO:Employee registered successfully
2021-06-10 16:48:19,027:ERROR:Error in address
2021-06-10 16:48:19,091:ERROR:Error in name
2021-06-10 16:48:19,139:INFO:Employee updated successfully
2021-06-10 16:48:19,147:ERROR:Error in updating employee address
2021-06-10 16:48:19,163:ERROR:Error in updating employee name
2021-06-10 16:48:19,188:INFO:Getting all employees attendance
2021-06-10 16:48:19,215:INFO:Getting employees attendance
2021-06-10 16:48:19,295:WARNING:Wrong session
2021-06-10 16:48:19,319:ERROR:Employee login fails
2021-06-10 16:48:19,343:INFO:Employee login successful
2021-06-10 16:48:19,359:ERROR:HR login fails
2021-06-10 16:48:19,367:INFO:HR login successful
2021-06-10 16:48:19,375:INFO:HR/employee session ends
2021-06-10 16:56:55,632:INFO:Getting employees details
2021-06-10 16:56:55,695:INFO:Update the employee
2021-06-10 16:56:55,726:INFO:Update the employee
2021-06-10 16:56:55,741:INFO:Employee updated successfully
2021-06-10 16:56:55,757:ERROR:Error in updating employee address
2021-06-10 16:56:55,773:ERROR:Error in updating employee name
2021-06-10 16:56:55,820:INFO:Employee registered successfully
2021-06-10 16:56:55,835:ERROR:Error in address
2021-06-10 16:56:55,851:ERROR:Error in name
2021-06-10 16:56:55,882:INFO:Employee updated successfully
2021-06-10 16:56:55,898:ERROR:Error in updating employee address
2021-06-10 16:56:55,913:ERROR:Error in updating employee name
2021-06-10 16:56:55,945:INFO:Getting all employees attendance
2021-06-10 16:56:55,991:INFO:Getting employees attendance
2021-06-10 16:56:56,085:WARNING:Wrong session
2021-06-10 16:56:56,116:ERROR:Employee login fails
2021-06-10 16:56:56,148:INFO:Employee login successful
2021-06-10 16:56:56,163:ERROR:HR login fails
2021-06-10 16:56:56,163:INFO:HR login successful
2021-06-10 16:56:56,179:INFO:HR/employee session ends
2021-06-10 16:58:23,182:INFO:Getting employees details
2021-06-10 16:58:23,260:INFO:Update the employee
2021-06-10 16:58:23,291:INFO:Update the employee
2021-06-10 16:58:23,307:INFO:Employee updated successfully
2021-06-10 16:58:23,322:ERROR:Error in updating employee address
2021-06-10 16:58:23,338:ERROR:Error in updating employee name
2021-06-10 16:58:23,369:INFO:Employee registered successfully
2021-06-10 16:58:23,369:ERROR:Error in address
2021-06-10 16:58:23,385:ERROR:Error in name
2021-06-10 16:58:23,400:INFO:Employee updated successfully
2021-06-10 16:58:23,416:ERROR:Error in updating employee address
2021-06-10 16:58:23,432:ERROR:Error in updating employee name
2021-06-10 16:58:23,447:INFO:Getting all employees attendance
2021-06-10 16:58:23,479:INFO:Getting employees attendance
2021-06-10 16:58:23,557:WARNING:Wrong session
2021-06-10 16:58:23,604:ERROR:Employee login fails
2021-06-10 16:58:23,635:INFO:Employee login successful
2021-06-10 16:58:23,650:ERROR:HR login fails
2021-06-10 16:58:23,666:INFO:HR login successful
2021-06-10 16:58:23,682:INFO:HR/employee session ends
2021-06-10 17:01:15,119:INFO:Getting employees details
2021-06-10 17:01:15,213:INFO:Update the employee
2021-06-10 17:01:15,244:INFO:Update the employee
2021-06-10 17:01:15,276:INFO:Employee updated successfully
2021-06-10 17:01:15,307:ERROR:Error in updating employee address
2021-06-10 17:01:15,323:ERROR:Error in updating employee name
2021-06-10 17:01:15,369:INFO:Employee registered successfully
2021-06-10 17:01:15,369:ERROR:Error in address
2021-06-10 17:01:15,385:ERROR:Error in name
2021-06-10 17:01:15,401:INFO:Employee updated successfully
2021-06-10 17:01:15,416:ERROR:Error in updating employee address
2021-06-10 17:01:15,432:ERROR:Error in updating employee name
2021-06-10 17:01:15,448:INFO:Getting all employees attendance
2021-06-10 17:01:15,479:INFO:Getting employees attendance
2021-06-10 17:01:15,573:WARNING:Wrong session
2021-06-10 17:01:15,619:ERROR:Employee login fails
2021-06-10 17:01:15,651:INFO:Employee login successful
2021-06-10 17:01:15,682:ERROR:HR login fails
2021-06-10 17:01:15,682:INFO:HR login successful
2021-06-10 17:01:15,698:INFO:HR/employee session ends
2021-06-10 17:01:37,572:INFO:Getting employees details
2021-06-10 17:01:37,666:INFO:Update the employee
2021-06-10 17:01:37,712:INFO:Update the employee
2021-06-10 17:01:37,744:INFO:Employee updated successfully
2021-06-10 17:01:37,791:ERROR:Error in updating employee address
2021-06-10 17:01:37,806:ERROR:Error in updating employee name
2021-06-10 17:01:37,853:INFO:Employee registered successfully
2021-06-10 17:01:37,869:ERROR:Error in address
2021-06-10 17:01:37,884:ERROR:Error in name
2021-06-10 17:01:37,900:INFO:Employee updated successfully
2021-06-10 17:01:37,931:ERROR:Error in updating employee address
2021-06-10 17:01:37,978:ERROR:Error in updating employee name
2021-06-10 17:01:38,041:INFO:Getting all employees attendance
2021-06-10 17:01:38,119:INFO:Getting employees attendance
2021-06-10 17:01:38,259:WARNING:Wrong session
2021-06-10 17:01:38,306:ERROR:Employee login fails
2021-06-10 17:01:38,322:INFO:Employee login successful
2021-06-10 17:01:38,353:ERROR:HR login fails
2021-06-10 17:01:38,369:INFO:HR login successful
2021-06-10 17:01:38,384:INFO:HR/employee session ends
